#pragma once

#include <array>
#include <cstddef>
#include <initializer_list>
#include <string>
#include <string_view>
#include <vector>

namespace pixatto {

enum class Language {
    English,
    Spanish,
    French,
    German,
    Danish,
    Swedish,
    Norwegian,
    Czech,
    Italian,
    Greek,
    Polish,
    Finnish,
    Ukrainian,
    Russian,
    ChineseSimplified,
    ChineseTraditional,
    Korean,
    Japanese,
    Count,
};

struct LanguageDefinition {
    Language language;
    const char* code;
    const char* english_name;
    const char* native_name;
};

enum class TextId {
    LanguageWindowTitle,
    ChooseLanguage,
    AboutWindowTitle,
    AboutButtonLabel,
    AboutButtonTooltip,
    HelpWindowTitle,
    HelpButtonLabel,
    HelpButtonTooltip,
    HelpSectionKeyboard,
    HelpSectionMouse,
    HelpSectionFiles,
    HelpUndo,
    HelpRedo,
    HelpNumericEntry,
    HelpImageZoom,
    HelpModelOrbit,
    HelpModelPan,
    HelpModelZoom,
    HelpModelReset,
    HelpModelOrigin,
    HelpTextureAssign,
    HelpDragDropFiles,
    AboutProjectCredit,
    AboutProjectLicense,
    AboutThirdPartyTitle,
    AboutDependenciesTitle,
    AboutDependencySdl,
    AboutDependencySdlImage,
    AboutDependencyImGui,
    AboutDependencyStb,
    AboutDependencyTinyGltf,
    AboutDependencyTinyObj,
    AboutDependencyUfbx,
    AboutDependencyTinyXml,
    AboutDependencyFfmpegExternal,
    AboutPalettesTitle,
    AboutPalettesCredit,
    AboutAssetsCredit,
    Close,
    CloseFile,
    CloseFileTooltip,
    Import,
    OpenImage,
    ImportPalette,
    ImportModel,
    Export,
    ExportPng,
    ExportRaw,
    BatchButton,
    BatchWindowTitle,
    BatchImages,
    BatchBrowseImages,
    BatchImagesDropHint,
    BatchImageCountFormat,
    BatchOutputFolder,
    BatchChooseFolder,
    BatchFormat,
    BatchPng,
    BatchRaw,
    BatchSuffix,
    BatchPreset,
    BatchCurrentSettings,
    BatchPixelize,
    Stop,
    TwoViews,
    OneView,
    ShowOriginalAndResult,
    ShowOnlyResult,
    StackViews,
    SideBySide,
    ShowResultTop,
    ShowOriginalLeft,
    Presets,
    NoPresetsSaved,
    SavePreset,
    DeletePreset,
    Pixelize,
    PixelSize,
    BlockSample,
    Average,
    Weighted,
    UsePalette,
    PreserveTransparency,
    NoPalettesSaved,
    UnsavedPalette,
    Palette,
    NewPalette,
    Save,
    SaveNew,
    DeletePalette,
    PaletteCountFormat,
    AddColorToBegin,
    EditColorFormat,
    AddColor,
    MaxColors,
    ColorLevels,
    Dithering,
    Mode,
    None,
    Bayer,
    BlueNoise,
    FloydSteinberg,
    FalseFloydSteinberg,
    FilterLite,
    ZhigangFan,
    ShiauFan,
    JarvisJudiceNinke,
    Atkinson,
    Stucki,
    Burkes,
    Sierra,
    TwoRowSierra,
    Riemersma,
    ClusterDot4x4,
    ClusterDot8x8,
    Horizontal2x2,
    Horizontal8x1,
    Horizontal12x4,
    Vertical2x2,
    Vertical1x8,
    Vertical4x12,
    Diagonal5x5,
    Pattern,
    Amount,
    Adjustments,
    Brightness,
    Contrast,
    Gamma,
    Saturation,
    InputBlack,
    InputWhite,
    OutputBlack,
    OutputWhite,
    Tint,
    TintStrength,
    ResetAdjustments,
    Result,
    Original,
    OriginalTextures,
    ModelMaterials,
    TextureDrawer,
    UntexturedGrey,
    TextureDrawerHint,
    DropTextureOnMaterial,
    ModelPreview,
    ResetView,
    ResetToOrigin,
    Zoom,
    Fit,
    NoImageLoaded,
    NoModelLoaded,
    NoModelTextures,
    SetNumericValue,
    Value,
    Apply,
    Cancel,
    InvalidValueFormat,
    SetValueFormat,
    OpenDroppedImageTitle,
    ReplaceDroppedImage,
    OpenDroppedFileTitle,
    ReplaceDroppedFile,
    Open,
    DeletePaletteTitle,
    DeleteSavedPalette,
    Delete,
    PaletteAlreadyExistsTitle,
    PaletteAlreadyExistsFormat,
    Overwrite,
    KeepBoth,
    NameImportedPaletteTitle,
    PaletteName,
    PaletteColorTitle,
    AddPaletteColor,
    EditPaletteColor,
    Add,
    DeleteColor,
    SavePaletteAsTitle,
    SavePresetAsTitle,
    PresetName,
    PresetAlreadyExistsTitle,
    PresetAlreadyExistsFormat,
    DeletePresetTitle,
    DeleteSavedPresetFormat,
    ImagesFilter,
    ModelsFilter,
    AllFilesFilter,
    LospecPalettesFilter,
    PngImageFilter,
    RawImageFilter,
    StatusFileDialogFailedFormat,
    StatusClosedFile,
    StatusOpenImageToBegin,
    StatusPreviewUpdatedFormat,
    StatusImageLoadFailedFormat,
    StatusLoadedFormat,
    StatusModelLoadFailedFormat,
    StatusModelLoadingFormat,
    StatusModelStillLoading,
    StatusModelLoadedFormat,
    StatusModelLoadedWithFallbackFormat,
    StatusModelTextureImportedFormat,
    StatusModelTextureAlreadyImportedFormat,
    StatusModelTextureAssignedFormat,
    StatusModelRenderFailedFormat,
    StatusModelRawExportUnavailable,
    StatusModelExportSkipped,
    StatusPaletteImportFailedFormat,
    StatusImportedPaletteFormat,
    StatusOverwrotePaletteFormat,
    StatusStartedNewPalette,
    StatusPaletteFull,
    StatusPaletteColorMissing,
    StatusUseSaveNew,
    StatusPaletteSaveFailedFormat,
    StatusSavedPaletteFormat,
    StatusAddColorBeforeSaving,
    StatusNoPaletteSelected,
    StatusPaletteDeleteFailedFormat,
    StatusDeletedPaletteFormat,
    StatusPresetSaveFailedFormat,
    StatusSavedPresetFormat,
    StatusOverwrotePresetFormat,
    StatusAppliedPresetFormat,
    StatusPresetDeleteFailedFormat,
    StatusDeletedPresetFormat,
    StatusExportSkipped,
    StatusExportFailedFormat,
    StatusExportedFormat,
    StatusBatchNoImages,
    StatusBatchNoOutputFolder,
    StatusBatchImagesAddedFormat,
    StatusBatchNoImagesAdded,
    StatusBatchStartedFormat,
    StatusBatchCompletedFormat,
    StatusBatchStoppedFormat,
    StatusNothingToUndo,
    StatusUndid,
    StatusNothingToRedo,
    StatusRedid,
    StatusAddedColor,
    StatusUpdatedColor,
    StatusDeletedColor,
    StatusSdlInitFailedFormat,
    StatusSdlCreateWindowFailedFormat,
    StatusSdlCreateRendererFailedFormat,
    StatusSdlCreateTextureFailedFormat,
    StatusRendererSetupFailedFormat,
    StatusTextureCreationFailedFormat,
    StatusLanguageChangedFormat,
    ImportVideo,
    ExportVideo,
    VideosFilter,
    NoVideoLoaded,
    VideoPreview,
    NoVideoFrame,
    Play,
    Pause,
    Timeline,
    VideoFrameFormat,
    VideoEncoding,
    VideoExportProgressFormat,
    VideoExportTimingFormat,
    VideoExportWindowTitle,
    VideoCodec,
    VideoContainer,
    VideoAudio,
    VideoNoAudio,
    VideoAudioCopy,
    VideoAudioAac,
    VideoAudioVorbis,
    VideoQualityCrf,
    VideoQualityQp,
    VideoHardwareSpeed,
    VideoHardwareSpeedBalanced,
    VideoHardwareSpeedFast,
    VideoHardwareSpeedVeryFast,
    VideoHardwareHint,
    VideoHardwareProbeRunning,
    VideoGpuProcessing,
    VideoGpuProcessingHint,
    VideoCpuRequiredProcessHint,
    VideoAudioIncompatible,
    VideoOutputSizeFormat,
    VideoOddDimensionWarning,
    VideoVfrWarning,
    StatusVideoExportSkipped,
    StatusVideoExportAlreadyRunning,
    StatusVideoNoExportProfiles,
    StatusVideoToolsMissingFormat,
    StatusVideoLoadFailedFormat,
    StatusVideoLoadedFormat,
    StatusVideoPreviewFailedFormat,
    StatusVideoPlaybackUnavailable,
    StatusVideoExportStartedFormat,
    StatusVideoExportFailedFormat,
    StatusVideoExportedFormat,
    Count,
};

enum class TranslationCatalogIssueKind {
    InvalidLanguageDefinition,
    MissingLanguageDefinition,
    DuplicateLanguageDefinition,
    InvalidTextId,
    MissingEnglishText,
    DuplicateText,
    EmptyText,
    MalformedPlaceholder,
    PlaceholderMismatch,
    PrintfPlaceholderMismatch,
};

struct TranslationCatalogIssue {
    TranslationCatalogIssueKind kind;
    Language language = Language::English;
    TextId id = TextId::Count;
    std::string message;
};

constexpr std::size_t kLanguageCount = static_cast<std::size_t>(Language::Count);
constexpr std::size_t kTextCount = static_cast<std::size_t>(TextId::Count);

const std::array<LanguageDefinition, kLanguageCount>& language_definitions();
const LanguageDefinition& language_definition(Language language);
const char* translate(Language language, TextId id);
[[nodiscard]] std::vector<TranslationCatalogIssue> validate_translation_catalog();
std::string format_translation(
    Language language,
    TextId id,
    std::initializer_list<std::pair<std::string_view, std::string_view>> values);

} // namespace pixatto
