#include "pixelizer/localization.hpp"

#include <string>

namespace pixelizer {
namespace {

struct Translation {
    TextId id;
    const char* text;
};

constexpr std::array<LanguageDefinition, kLanguageCount> kLanguages = {{
    {Language::English, "en", "English", "English"},
    {Language::Spanish, "es", "Spanish", "Español"},
    {Language::French, "fr", "French", "Français"},
    {Language::German, "de", "German", "Deutsch"},
    {Language::Danish, "da", "Danish", "Dansk"},
    {Language::Swedish, "sv", "Swedish", "Svenska"},
    {Language::Norwegian, "nb", "Norwegian", "Norsk"},
    {Language::Czech, "cs", "Czech", "Čeština"},
    {Language::Italian, "it", "Italian", "Italiano"},
    {Language::Greek, "el", "Greek", "Ελληνικά"},
    {Language::Polish, "pl", "Polish", "Polski"},
    {Language::Finnish, "fi", "Finnish", "Suomi"},
    {Language::Ukrainian, "uk", "Ukrainian", "Українська"},
    {Language::Russian, "ru", "Russian", "Русский"},
    {Language::ChineseSimplified, "zh-Hans", "Chinese (Simplified)", "简体中文"},
    {Language::ChineseTraditional, "zh-Hant", "Chinese (Traditional)", "繁體中文"},
    {Language::Korean, "ko", "Korean", "한국어"},
    {Language::Japanese, "ja", "Japanese", "日本語"},
}};

constexpr Translation kEnglish[] = {
    {TextId::LanguageWindowTitle, "Language"},
    {TextId::ChooseLanguage, "Choose a language"},
    {TextId::AboutWindowTitle, "About Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "About Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer by Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Released under the MIT License."},
    {TextId::AboutThirdPartyTitle, "Third-party licenses and credits"},
    {TextId::AboutDependenciesTitle, "Dependencies"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 from libsdl-org/SDL, under the zlib license."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 from ocornut/imgui, under the MIT license."},
    {TextId::AboutDependencyStb, "stb at commit 31c1ad37456438565541f4919958214b6e762fb4 from nothings/stb, using its public-domain/MIT dual license."},
    {TextId::AboutPalettesTitle, "Bundled palettes"},
    {TextId::AboutPalettesCredit, "Default palette files are bundled from Lospec. Original palette page links are listed in THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "The README screenshot and icon files are original project assets."},
    {TextId::Close, "Close"},
    {TextId::OpenImage, "Open Image"},
    {TextId::ImportPalette, "Import Palette"},
    {TextId::ExportPng, "Export PNG"},
    {TextId::TwoViews, "Two Views"},
    {TextId::OneView, "One View"},
    {TextId::ShowOriginalAndResult, "Show original and result viewports."},
    {TextId::ShowOnlyResult, "Show only the result viewport."},
    {TextId::StackViews, "Stack Views"},
    {TextId::SideBySide, "Side by Side"},
    {TextId::ShowResultTop, "Show result on top and original on bottom."},
    {TextId::ShowOriginalLeft, "Show original left and result right."},
    {TextId::Pixelize, "Pixelize"},
    {TextId::PixelSize, "Pixel size"},
    {TextId::BlockSample, "Block sample"},
    {TextId::Average, "Average"},
    {TextId::Weighted, "Weighted"},
    {TextId::UsePalette, "Use palette"},
    {TextId::PreserveTransparency, "Preserve transparency"},
    {TextId::NoPalettesSaved, "No palettes saved."},
    {TextId::UnsavedPalette, "Unsaved palette"},
    {TextId::Palette, "Palette"},
    {TextId::NewPalette, "New Palette"},
    {TextId::Save, "Save"},
    {TextId::SaveNew, "Save New"},
    {TextId::DeletePalette, "Delete Palette"},
    {TextId::PaletteCountFormat, "%zu / %zu colors"},
    {TextId::AddColorToBegin, "Add a color to begin."},
    {TextId::EditColorFormat, "Edit color {index}"},
    {TextId::AddColor, "Add color"},
    {TextId::MaxColors, "Max colors"},
    {TextId::ColorLevels, "Color levels"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Mode"},
    {TextId::None, "None"},
    {TextId::Bayer, "Bayer"},
    {TextId::BlueNoise, "Blue Noise"},
    {TextId::FloydSteinberg, "Floyd-Steinberg"},
    {TextId::JarvisJudiceNinke, "Jarvis-Judice-Ninke"},
    {TextId::Atkinson, "Atkinson"},
    {TextId::Riemersma, "Riemersma"},
    {TextId::Pattern, "Pattern"},
    {TextId::Amount, "Amount"},
    {TextId::Adjustments, "Adjustments"},
    {TextId::Brightness, "Brightness"},
    {TextId::Contrast, "Contrast"},
    {TextId::Gamma, "Gamma"},
    {TextId::Saturation, "Saturation"},
    {TextId::InputBlack, "Input black"},
    {TextId::InputWhite, "Input white"},
    {TextId::OutputBlack, "Output black"},
    {TextId::OutputWhite, "Output white"},
    {TextId::Tint, "Tint"},
    {TextId::TintStrength, "Tint strength"},
    {TextId::ResetAdjustments, "Reset Adjustments"},
    {TextId::Result, "Result"},
    {TextId::Original, "Original"},
    {TextId::Zoom, "Zoom"},
    {TextId::Fit, "Fit"},
    {TextId::NoImageLoaded, "No image loaded"},
    {TextId::SetNumericValue, "Set numeric value"},
    {TextId::Value, "Value"},
    {TextId::Apply, "Apply"},
    {TextId::Cancel, "Cancel"},
    {TextId::InvalidValueFormat, "Invalid value for {label}."},
    {TextId::SetValueFormat, "Set {label}."},
    {TextId::OpenDroppedImageTitle, "Open dropped image?"},
    {TextId::ReplaceDroppedImage, "Replace the current image with the dropped image?"},
    {TextId::Open, "Open"},
    {TextId::DeletePaletteTitle, "Delete palette?"},
    {TextId::DeleteSavedPalette, "Delete this saved palette?"},
    {TextId::Delete, "Delete"},
    {TextId::PaletteAlreadyExistsTitle, "Palette already exists"},
    {TextId::PaletteAlreadyExistsFormat, "{name} already exists."},
    {TextId::Overwrite, "Overwrite"},
    {TextId::KeepBoth, "Keep both"},
    {TextId::NameImportedPaletteTitle, "Name imported palette"},
    {TextId::PaletteName, "Palette name"},
    {TextId::PaletteColorTitle, "Palette color"},
    {TextId::AddPaletteColor, "Add palette color"},
    {TextId::EditPaletteColor, "Edit palette color"},
    {TextId::Add, "Add"},
    {TextId::DeleteColor, "Delete Color"},
    {TextId::SavePaletteAsTitle, "Save palette as"},
    {TextId::ImagesFilter, "Images"},
    {TextId::AllFilesFilter, "All files"},
    {TextId::LospecPalettesFilter, "Lospec palettes"},
    {TextId::PngImageFilter, "PNG image"},
    {TextId::StatusFileDialogFailedFormat, "File dialog failed: {error}"},
    {TextId::StatusOpenImageToBegin, "Open an image to begin."},
    {TextId::StatusPreviewUpdatedFormat, "Preview updated in {ms} ms."},
    {TextId::StatusImageLoadFailedFormat, "Image load failed: {error}"},
    {TextId::StatusLoadedFormat, "Loaded {name}."},
    {TextId::StatusPaletteImportFailedFormat, "Palette import failed: {error}"},
    {TextId::StatusImportedPaletteFormat, "Imported palette {name}."},
    {TextId::StatusOverwrotePaletteFormat, "Overwrote palette {name}."},
    {TextId::StatusStartedNewPalette, "Started a new unsaved palette."},
    {TextId::StatusPaletteFull, "Palette already has 256 colors."},
    {TextId::StatusPaletteColorMissing, "Palette color no longer exists."},
    {TextId::StatusUseSaveNew, "Use Save New for unsaved palettes."},
    {TextId::StatusPaletteSaveFailedFormat, "Palette save failed: {error}"},
    {TextId::StatusSavedPaletteFormat, "Saved palette {name}."},
    {TextId::StatusAddColorBeforeSaving, "Add at least one color before saving."},
    {TextId::StatusNoPaletteSelected, "No palette selected."},
    {TextId::StatusPaletteDeleteFailedFormat, "Palette delete failed: {error}"},
    {TextId::StatusDeletedPaletteFormat, "Deleted palette {name}."},
    {TextId::StatusExportSkipped, "Export skipped: no result image yet."},
    {TextId::StatusExportFailedFormat, "Export failed: {error}"},
    {TextId::StatusExportedFormat, "Exported {name}."},
    {TextId::StatusNothingToUndo, "Nothing to undo."},
    {TextId::StatusUndid, "Undid last edit."},
    {TextId::StatusNothingToRedo, "Nothing to redo."},
    {TextId::StatusRedid, "Redid last edit."},
    {TextId::StatusAddedColor, "Added palette color."},
    {TextId::StatusUpdatedColor, "Updated palette color."},
    {TextId::StatusDeletedColor, "Deleted palette color."},
    {TextId::StatusSdlInitFailedFormat, "SDL_Init failed: {error}"},
    {TextId::StatusSdlCreateWindowFailedFormat, "SDL_CreateWindow failed: {error}"},
    {TextId::StatusSdlCreateRendererFailedFormat, "SDL_CreateRenderer failed: {error}"},
    {TextId::StatusSdlCreateTextureFailedFormat, "SDL_CreateTexture failed: {error}"},
    {TextId::StatusLanguageChangedFormat, "Language changed to {language}."},
};

constexpr Translation kSpanish[] = {
    {TextId::LanguageWindowTitle, "Idioma"},
    {TextId::ChooseLanguage, "Elige un idioma"},
    {TextId::AboutWindowTitle, "Acerca de Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Acerca de Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer de Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Publicado bajo la licencia MIT."},
    {TextId::AboutThirdPartyTitle, "Licencias y créditos de terceros"},
    {TextId::AboutDependenciesTitle, "Dependencias"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 de libsdl-org/SDL, bajo la licencia zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 de ocornut/imgui, bajo la licencia MIT."},
    {TextId::AboutDependencyStb, "stb en el commit 31c1ad37456438565541f4919958214b6e762fb4 de nothings/stb, con licencia dual dominio público/MIT."},
    {TextId::AboutPalettesTitle, "Paletas incluidas"},
    {TextId::AboutPalettesCredit, "Los archivos de paleta predeterminados se incluyen desde Lospec. Los enlaces a las páginas originales figuran en THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "La captura del README y los iconos son recursos originales del proyecto."},
    {TextId::Close, "Cerrar"},
    {TextId::OpenImage, "Abrir imagen"},
    {TextId::ImportPalette, "Importar paleta"},
    {TextId::ExportPng, "Exportar PNG"},
    {TextId::TwoViews, "Dos vistas"},
    {TextId::OneView, "Una vista"},
    {TextId::ShowOriginalAndResult, "Mostrar las vistas original y resultado."},
    {TextId::ShowOnlyResult, "Mostrar solo la vista del resultado."},
    {TextId::StackViews, "Apilar vistas"},
    {TextId::SideBySide, "Lado a lado"},
    {TextId::ShowResultTop, "Mostrar el resultado arriba y el original abajo."},
    {TextId::ShowOriginalLeft, "Mostrar el original a la izquierda y el resultado a la derecha."},
    {TextId::Pixelize, "Pixelar"},
    {TextId::PixelSize, "Tamaño de píxel"},
    {TextId::BlockSample, "Muestra de bloque"},
    {TextId::Average, "Promedio"},
    {TextId::Weighted, "Ponderado"},
    {TextId::UsePalette, "Usar paleta"},
    {TextId::PreserveTransparency, "Conservar transparencia"},
    {TextId::NoPalettesSaved, "No hay paletas guardadas."},
    {TextId::UnsavedPalette, "Paleta sin guardar"},
    {TextId::Palette, "Paleta"},
    {TextId::NewPalette, "Nueva paleta"},
    {TextId::Save, "Guardar"},
    {TextId::SaveNew, "Guardar nueva"},
    {TextId::DeletePalette, "Eliminar paleta"},
    {TextId::PaletteCountFormat, "%zu / %zu colores"},
    {TextId::AddColorToBegin, "Añade un color para empezar."},
    {TextId::EditColorFormat, "Editar color {index}"},
    {TextId::AddColor, "Añadir color"},
    {TextId::MaxColors, "Colores máximos"},
    {TextId::ColorLevels, "Niveles de color"},
    {TextId::Dithering, "Tramado"},
    {TextId::Mode, "Modo"},
    {TextId::None, "Ninguno"},
    {TextId::Pattern, "Patrón"},
    {TextId::Amount, "Cantidad"},
    {TextId::Adjustments, "Ajustes"},
    {TextId::Brightness, "Brillo"},
    {TextId::Contrast, "Contraste"},
    {TextId::Gamma, "Gamma"},
    {TextId::Saturation, "Saturación"},
    {TextId::InputBlack, "Negro de entrada"},
    {TextId::InputWhite, "Blanco de entrada"},
    {TextId::OutputBlack, "Negro de salida"},
    {TextId::OutputWhite, "Blanco de salida"},
    {TextId::Tint, "Tinte"},
    {TextId::TintStrength, "Intensidad del tinte"},
    {TextId::ResetAdjustments, "Restablecer ajustes"},
    {TextId::Result, "Resultado"},
    {TextId::Original, "Original"},
    {TextId::Zoom, "Zoom"},
    {TextId::Fit, "Ajustar"},
    {TextId::NoImageLoaded, "No hay imagen cargada"},
    {TextId::SetNumericValue, "Definir valor numérico"},
    {TextId::Value, "Valor"},
    {TextId::Apply, "Aplicar"},
    {TextId::Cancel, "Cancelar"},
    {TextId::InvalidValueFormat, "Valor no válido para {label}."},
    {TextId::SetValueFormat, "{label} definido."},
    {TextId::OpenDroppedImageTitle, "¿Abrir imagen soltada?"},
    {TextId::ReplaceDroppedImage, "¿Reemplazar la imagen actual por la imagen soltada?"},
    {TextId::Open, "Abrir"},
    {TextId::DeletePaletteTitle, "¿Eliminar paleta?"},
    {TextId::DeleteSavedPalette, "¿Eliminar esta paleta guardada?"},
    {TextId::Delete, "Eliminar"},
    {TextId::PaletteAlreadyExistsTitle, "La paleta ya existe"},
    {TextId::PaletteAlreadyExistsFormat, "{name} ya existe."},
    {TextId::Overwrite, "Sobrescribir"},
    {TextId::KeepBoth, "Conservar ambas"},
    {TextId::NameImportedPaletteTitle, "Nombrar paleta importada"},
    {TextId::PaletteName, "Nombre de la paleta"},
    {TextId::PaletteColorTitle, "Color de paleta"},
    {TextId::AddPaletteColor, "Añadir color de paleta"},
    {TextId::EditPaletteColor, "Editar color de paleta"},
    {TextId::Add, "Añadir"},
    {TextId::DeleteColor, "Eliminar color"},
    {TextId::SavePaletteAsTitle, "Guardar paleta como"},
    {TextId::ImagesFilter, "Imágenes"},
    {TextId::AllFilesFilter, "Todos los archivos"},
    {TextId::LospecPalettesFilter, "Paletas Lospec"},
    {TextId::PngImageFilter, "Imagen PNG"},
    {TextId::StatusOpenImageToBegin, "Abre una imagen para empezar."},
    {TextId::StatusPreviewUpdatedFormat, "Vista previa actualizada en {ms} ms."},
    {TextId::StatusImageLoadFailedFormat, "Error al cargar la imagen: {error}"},
    {TextId::StatusLoadedFormat, "{name} cargado."},
    {TextId::StatusPaletteImportFailedFormat, "Error al importar la paleta: {error}"},
    {TextId::StatusImportedPaletteFormat, "Paleta {name} importada."},
    {TextId::StatusOverwrotePaletteFormat, "Paleta {name} sobrescrita."},
    {TextId::StatusStartedNewPalette, "Se inició una paleta nueva sin guardar."},
    {TextId::StatusPaletteFull, "La paleta ya tiene 256 colores."},
    {TextId::StatusPaletteColorMissing, "El color de la paleta ya no existe."},
    {TextId::StatusUseSaveNew, "Usa Guardar nueva para paletas sin guardar."},
    {TextId::StatusPaletteSaveFailedFormat, "Error al guardar la paleta: {error}"},
    {TextId::StatusSavedPaletteFormat, "Paleta {name} guardada."},
    {TextId::StatusAddColorBeforeSaving, "Añade al menos un color antes de guardar."},
    {TextId::StatusNoPaletteSelected, "No hay ninguna paleta seleccionada."},
    {TextId::StatusPaletteDeleteFailedFormat, "Error al eliminar la paleta: {error}"},
    {TextId::StatusDeletedPaletteFormat, "Paleta {name} eliminada."},
    {TextId::StatusExportSkipped, "Exportación omitida: aún no hay imagen resultante."},
    {TextId::StatusExportFailedFormat, "Error al exportar: {error}"},
    {TextId::StatusExportedFormat, "{name} exportado."},
    {TextId::StatusNothingToUndo, "Nada que deshacer."},
    {TextId::StatusUndid, "Última edición deshecha."},
    {TextId::StatusNothingToRedo, "Nada que rehacer."},
    {TextId::StatusRedid, "Última edición rehecha."},
    {TextId::StatusAddedColor, "Color de paleta añadido."},
    {TextId::StatusUpdatedColor, "Color de paleta actualizado."},
    {TextId::StatusDeletedColor, "Color de paleta eliminado."},
    {TextId::StatusLanguageChangedFormat, "Idioma cambiado a {language}."},
};

constexpr Translation kFrench[] = {
    {TextId::LanguageWindowTitle, "Langue"},
    {TextId::ChooseLanguage, "Choisir une langue"},
    {TextId::AboutWindowTitle, "À propos de Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "À propos de Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer par Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Publié sous licence MIT."},
    {TextId::AboutThirdPartyTitle, "Licences et crédits tiers"},
    {TextId::AboutDependenciesTitle, "Dépendances"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 de libsdl-org/SDL, sous licence zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 de ocornut/imgui, sous licence MIT."},
    {TextId::AboutDependencyStb, "stb au commit 31c1ad37456438565541f4919958214b6e762fb4 de nothings/stb, sous double licence domaine public/MIT."},
    {TextId::AboutPalettesTitle, "Palettes incluses"},
    {TextId::AboutPalettesCredit, "Les fichiers de palette par défaut proviennent de Lospec. Les liens vers les pages originales sont listés dans THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "La capture du README et les icônes sont des ressources originales du projet."},
    {TextId::Close, "Fermer"},
    {TextId::OpenImage, "Ouvrir l'image"},
    {TextId::ImportPalette, "Importer une palette"},
    {TextId::ExportPng, "Exporter PNG"},
    {TextId::TwoViews, "Deux vues"},
    {TextId::OneView, "Une vue"},
    {TextId::ShowOriginalAndResult, "Afficher les vues original et résultat."},
    {TextId::ShowOnlyResult, "Afficher seulement la vue du résultat."},
    {TextId::StackViews, "Empiler les vues"},
    {TextId::SideBySide, "Côte à côte"},
    {TextId::ShowResultTop, "Afficher le résultat en haut et l'original en bas."},
    {TextId::ShowOriginalLeft, "Afficher l'original à gauche et le résultat à droite."},
    {TextId::Pixelize, "Pixelliser"},
    {TextId::PixelSize, "Taille des pixels"},
    {TextId::BlockSample, "Échantillon de bloc"},
    {TextId::Average, "Moyenne"},
    {TextId::Weighted, "Pondéré"},
    {TextId::UsePalette, "Utiliser une palette"},
    {TextId::PreserveTransparency, "Conserver la transparence"},
    {TextId::NoPalettesSaved, "Aucune palette enregistrée."},
    {TextId::UnsavedPalette, "Palette non enregistrée"},
    {TextId::Palette, "Palette"},
    {TextId::NewPalette, "Nouvelle palette"},
    {TextId::Save, "Enregistrer"},
    {TextId::SaveNew, "Enregistrer une copie"},
    {TextId::DeletePalette, "Supprimer la palette"},
    {TextId::PaletteCountFormat, "%zu / %zu couleurs"},
    {TextId::AddColorToBegin, "Ajoutez une couleur pour commencer."},
    {TextId::EditColorFormat, "Modifier la couleur {index}"},
    {TextId::AddColor, "Ajouter une couleur"},
    {TextId::MaxColors, "Couleurs max."},
    {TextId::ColorLevels, "Niveaux de couleur"},
    {TextId::Dithering, "Tramage"},
    {TextId::Mode, "Mode"},
    {TextId::None, "Aucun"},
    {TextId::Pattern, "Motif"},
    {TextId::Amount, "Quantité"},
    {TextId::Adjustments, "Réglages"},
    {TextId::Brightness, "Luminosité"},
    {TextId::Contrast, "Contraste"},
    {TextId::Gamma, "Gamma"},
    {TextId::Saturation, "Saturation"},
    {TextId::InputBlack, "Noir d'entrée"},
    {TextId::InputWhite, "Blanc d'entrée"},
    {TextId::OutputBlack, "Noir de sortie"},
    {TextId::OutputWhite, "Blanc de sortie"},
    {TextId::Tint, "Teinte"},
    {TextId::TintStrength, "Force de la teinte"},
    {TextId::ResetAdjustments, "Réinitialiser les réglages"},
    {TextId::Result, "Résultat"},
    {TextId::Original, "Original"},
    {TextId::Zoom, "Zoom"},
    {TextId::Fit, "Ajuster"},
    {TextId::NoImageLoaded, "Aucune image chargée"},
    {TextId::SetNumericValue, "Définir une valeur numérique"},
    {TextId::Value, "Valeur"},
    {TextId::Apply, "Appliquer"},
    {TextId::Cancel, "Annuler"},
    {TextId::InvalidValueFormat, "Valeur invalide pour {label}."},
    {TextId::SetValueFormat, "{label} défini."},
    {TextId::OpenDroppedImageTitle, "Ouvrir l'image déposée ?"},
    {TextId::ReplaceDroppedImage, "Remplacer l'image actuelle par l'image déposée ?"},
    {TextId::Open, "Ouvrir"},
    {TextId::DeletePaletteTitle, "Supprimer la palette ?"},
    {TextId::DeleteSavedPalette, "Supprimer cette palette enregistrée ?"},
    {TextId::Delete, "Supprimer"},
    {TextId::PaletteAlreadyExistsTitle, "La palette existe déjà"},
    {TextId::PaletteAlreadyExistsFormat, "{name} existe déjà."},
    {TextId::Overwrite, "Remplacer"},
    {TextId::KeepBoth, "Garder les deux"},
    {TextId::NameImportedPaletteTitle, "Nommer la palette importée"},
    {TextId::PaletteName, "Nom de la palette"},
    {TextId::PaletteColorTitle, "Couleur de palette"},
    {TextId::AddPaletteColor, "Ajouter une couleur de palette"},
    {TextId::EditPaletteColor, "Modifier une couleur de palette"},
    {TextId::Add, "Ajouter"},
    {TextId::DeleteColor, "Supprimer la couleur"},
    {TextId::SavePaletteAsTitle, "Enregistrer la palette sous"},
    {TextId::ImagesFilter, "Images"},
    {TextId::AllFilesFilter, "Tous les fichiers"},
    {TextId::LospecPalettesFilter, "Palettes Lospec"},
    {TextId::PngImageFilter, "Image PNG"},
    {TextId::StatusOpenImageToBegin, "Ouvrez une image pour commencer."},
    {TextId::StatusPreviewUpdatedFormat, "Aperçu mis à jour en {ms} ms."},
    {TextId::StatusImageLoadFailedFormat, "Échec du chargement de l'image : {error}"},
    {TextId::StatusLoadedFormat, "{name} chargé."},
    {TextId::StatusPaletteImportFailedFormat, "Échec de l'import de la palette : {error}"},
    {TextId::StatusImportedPaletteFormat, "Palette {name} importée."},
    {TextId::StatusOverwrotePaletteFormat, "Palette {name} remplacée."},
    {TextId::StatusStartedNewPalette, "Nouvelle palette non enregistrée commencée."},
    {TextId::StatusPaletteFull, "La palette contient déjà 256 couleurs."},
    {TextId::StatusPaletteColorMissing, "Cette couleur de palette n'existe plus."},
    {TextId::StatusUseSaveNew, "Utilisez Enregistrer une copie pour les palettes non enregistrées."},
    {TextId::StatusPaletteSaveFailedFormat, "Échec de l'enregistrement de la palette : {error}"},
    {TextId::StatusSavedPaletteFormat, "Palette {name} enregistrée."},
    {TextId::StatusAddColorBeforeSaving, "Ajoutez au moins une couleur avant d'enregistrer."},
    {TextId::StatusNoPaletteSelected, "Aucune palette sélectionnée."},
    {TextId::StatusPaletteDeleteFailedFormat, "Échec de la suppression de la palette : {error}"},
    {TextId::StatusDeletedPaletteFormat, "Palette {name} supprimée."},
    {TextId::StatusExportSkipped, "Export ignoré : aucune image de résultat."},
    {TextId::StatusExportFailedFormat, "Échec de l'export : {error}"},
    {TextId::StatusExportedFormat, "{name} exporté."},
    {TextId::StatusNothingToUndo, "Rien à annuler."},
    {TextId::StatusUndid, "Dernière modification annulée."},
    {TextId::StatusNothingToRedo, "Rien à rétablir."},
    {TextId::StatusRedid, "Dernière modification rétablie."},
    {TextId::StatusAddedColor, "Couleur de palette ajoutée."},
    {TextId::StatusUpdatedColor, "Couleur de palette mise à jour."},
    {TextId::StatusDeletedColor, "Couleur de palette supprimée."},
    {TextId::StatusLanguageChangedFormat, "Langue changée en {language}."},
};

constexpr Translation kGerman[] = {
    {TextId::LanguageWindowTitle, "Sprache"},
    {TextId::ChooseLanguage, "Sprache auswählen"},
    {TextId::AboutWindowTitle, "Über Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Über Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer von Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Veröffentlicht unter der MIT-Lizenz."},
    {TextId::AboutThirdPartyTitle, "Lizenzen und Danksagungen Dritter"},
    {TextId::AboutDependenciesTitle, "Abhängigkeiten"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 von libsdl-org/SDL, unter der zlib-Lizenz."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 von ocornut/imgui, unter der MIT-Lizenz."},
    {TextId::AboutDependencyStb, "stb bei Commit 31c1ad37456438565541f4919958214b6e762fb4 von nothings/stb, unter Public-Domain/MIT-Doppellizenz."},
    {TextId::AboutPalettesTitle, "Mitgelieferte Paletten"},
    {TextId::AboutPalettesCredit, "Die Standard-Palettendateien stammen von Lospec. Links zu den Originalseiten stehen in THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Der README-Screenshot und die Symboldateien sind originale Projektressourcen."},
    {TextId::Close, "Schließen"},
    {TextId::OpenImage, "Bild öffnen"},
    {TextId::ImportPalette, "Palette importieren"},
    {TextId::ExportPng, "PNG exportieren"},
    {TextId::TwoViews, "Zwei Ansichten"},
    {TextId::OneView, "Eine Ansicht"},
    {TextId::ShowOriginalAndResult, "Original- und Ergebnisansicht anzeigen."},
    {TextId::ShowOnlyResult, "Nur die Ergebnisansicht anzeigen."},
    {TextId::StackViews, "Ansichten stapeln"},
    {TextId::SideBySide, "Nebeneinander"},
    {TextId::ShowResultTop, "Ergebnis oben und Original unten anzeigen."},
    {TextId::ShowOriginalLeft, "Original links und Ergebnis rechts anzeigen."},
    {TextId::Pixelize, "Pixelisieren"},
    {TextId::PixelSize, "Pixelgröße"},
    {TextId::BlockSample, "Blockprobe"},
    {TextId::Average, "Durchschnitt"},
    {TextId::Weighted, "Gewichtet"},
    {TextId::UsePalette, "Palette verwenden"},
    {TextId::PreserveTransparency, "Transparenz beibehalten"},
    {TextId::NoPalettesSaved, "Keine Paletten gespeichert."},
    {TextId::UnsavedPalette, "Ungespeicherte Palette"},
    {TextId::Palette, "Palette"},
    {TextId::NewPalette, "Neue Palette"},
    {TextId::Save, "Speichern"},
    {TextId::SaveNew, "Neu speichern"},
    {TextId::DeletePalette, "Palette löschen"},
    {TextId::PaletteCountFormat, "%zu / %zu Farben"},
    {TextId::AddColorToBegin, "Füge zuerst eine Farbe hinzu."},
    {TextId::EditColorFormat, "Farbe {index} bearbeiten"},
    {TextId::AddColor, "Farbe hinzufügen"},
    {TextId::MaxColors, "Max. Farben"},
    {TextId::ColorLevels, "Farbstufen"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Modus"},
    {TextId::None, "Keine"},
    {TextId::Pattern, "Muster"},
    {TextId::Amount, "Stärke"},
    {TextId::Adjustments, "Anpassungen"},
    {TextId::Brightness, "Helligkeit"},
    {TextId::Contrast, "Kontrast"},
    {TextId::Gamma, "Gamma"},
    {TextId::Saturation, "Sättigung"},
    {TextId::InputBlack, "Eingabe-Schwarz"},
    {TextId::InputWhite, "Eingabe-Weiß"},
    {TextId::OutputBlack, "Ausgabe-Schwarz"},
    {TextId::OutputWhite, "Ausgabe-Weiß"},
    {TextId::Tint, "Farbton"},
    {TextId::TintStrength, "Farbtonstärke"},
    {TextId::ResetAdjustments, "Anpassungen zurücksetzen"},
    {TextId::Result, "Ergebnis"},
    {TextId::Original, "Original"},
    {TextId::Zoom, "Zoom"},
    {TextId::Fit, "Einpassen"},
    {TextId::NoImageLoaded, "Kein Bild geladen"},
    {TextId::SetNumericValue, "Zahlenwert festlegen"},
    {TextId::Value, "Wert"},
    {TextId::Apply, "Anwenden"},
    {TextId::Cancel, "Abbrechen"},
    {TextId::InvalidValueFormat, "Ungültiger Wert für {label}."},
    {TextId::SetValueFormat, "{label} gesetzt."},
    {TextId::OpenDroppedImageTitle, "Abgelegtes Bild öffnen?"},
    {TextId::ReplaceDroppedImage, "Aktuelles Bild durch das abgelegte Bild ersetzen?"},
    {TextId::Open, "Öffnen"},
    {TextId::DeletePaletteTitle, "Palette löschen?"},
    {TextId::DeleteSavedPalette, "Diese gespeicherte Palette löschen?"},
    {TextId::Delete, "Löschen"},
    {TextId::PaletteAlreadyExistsTitle, "Palette existiert bereits"},
    {TextId::PaletteAlreadyExistsFormat, "{name} existiert bereits."},
    {TextId::Overwrite, "Überschreiben"},
    {TextId::KeepBoth, "Beide behalten"},
    {TextId::NameImportedPaletteTitle, "Importierte Palette benennen"},
    {TextId::PaletteName, "Palettenname"},
    {TextId::PaletteColorTitle, "Palettenfarbe"},
    {TextId::AddPaletteColor, "Palettenfarbe hinzufügen"},
    {TextId::EditPaletteColor, "Palettenfarbe bearbeiten"},
    {TextId::Add, "Hinzufügen"},
    {TextId::DeleteColor, "Farbe löschen"},
    {TextId::SavePaletteAsTitle, "Palette speichern unter"},
    {TextId::ImagesFilter, "Bilder"},
    {TextId::AllFilesFilter, "Alle Dateien"},
    {TextId::LospecPalettesFilter, "Lospec-Paletten"},
    {TextId::PngImageFilter, "PNG-Bild"},
    {TextId::StatusOpenImageToBegin, "Öffne ein Bild, um zu beginnen."},
    {TextId::StatusPreviewUpdatedFormat, "Vorschau in {ms} ms aktualisiert."},
    {TextId::StatusImageLoadFailedFormat, "Bild konnte nicht geladen werden: {error}"},
    {TextId::StatusLoadedFormat, "{name} geladen."},
    {TextId::StatusPaletteImportFailedFormat, "Palettenimport fehlgeschlagen: {error}"},
    {TextId::StatusImportedPaletteFormat, "Palette {name} importiert."},
    {TextId::StatusOverwrotePaletteFormat, "Palette {name} überschrieben."},
    {TextId::StatusStartedNewPalette, "Neue ungespeicherte Palette begonnen."},
    {TextId::StatusPaletteFull, "Die Palette hat bereits 256 Farben."},
    {TextId::StatusPaletteColorMissing, "Die Palettenfarbe existiert nicht mehr."},
    {TextId::StatusUseSaveNew, "Verwende Neu speichern für ungespeicherte Paletten."},
    {TextId::StatusPaletteSaveFailedFormat, "Palette konnte nicht gespeichert werden: {error}"},
    {TextId::StatusSavedPaletteFormat, "Palette {name} gespeichert."},
    {TextId::StatusAddColorBeforeSaving, "Füge vor dem Speichern mindestens eine Farbe hinzu."},
    {TextId::StatusNoPaletteSelected, "Keine Palette ausgewählt."},
    {TextId::StatusPaletteDeleteFailedFormat, "Palette konnte nicht gelöscht werden: {error}"},
    {TextId::StatusDeletedPaletteFormat, "Palette {name} gelöscht."},
    {TextId::StatusExportSkipped, "Export übersprungen: noch kein Ergebnisbild."},
    {TextId::StatusExportFailedFormat, "Export fehlgeschlagen: {error}"},
    {TextId::StatusExportedFormat, "{name} exportiert."},
    {TextId::StatusNothingToUndo, "Nichts rückgängig zu machen."},
    {TextId::StatusUndid, "Letzte Änderung rückgängig gemacht."},
    {TextId::StatusNothingToRedo, "Nichts zu wiederholen."},
    {TextId::StatusRedid, "Letzte Änderung wiederholt."},
    {TextId::StatusAddedColor, "Palettenfarbe hinzugefügt."},
    {TextId::StatusUpdatedColor, "Palettenfarbe aktualisiert."},
    {TextId::StatusDeletedColor, "Palettenfarbe gelöscht."},
    {TextId::StatusLanguageChangedFormat, "Sprache auf {language} geändert."},
};

constexpr Translation kDanish[] = {
    {TextId::LanguageWindowTitle, "Sprog"},
    {TextId::ChooseLanguage, "Vælg et sprog"},
    {TextId::AboutWindowTitle, "Om Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Om Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer af Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Udgivet under MIT-licensen."},
    {TextId::AboutThirdPartyTitle, "Tredjepartslicenser og krediteringer"},
    {TextId::AboutDependenciesTitle, "Afhængigheder"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 fra libsdl-org/SDL, under zlib-licensen."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 fra ocornut/imgui, under MIT-licensen."},
    {TextId::AboutDependencyStb, "stb ved commit 31c1ad37456438565541f4919958214b6e762fb4 fra nothings/stb, med public-domain/MIT-dobbeltlicens."},
    {TextId::AboutPalettesTitle, "Medfølgende paletter"},
    {TextId::AboutPalettesCredit, "Standardpalettefilerne er bundtet fra Lospec. Links til de originale palettesider findes i THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "README-skærmbilledet og ikonfilerne er originale projektaktiver."},
    {TextId::Close, "Luk"},
    {TextId::OpenImage, "Åbn billede"},
    {TextId::ImportPalette, "Importér palette"},
    {TextId::ExportPng, "Eksportér PNG"},
    {TextId::TwoViews, "To visninger"},
    {TextId::OneView, "Én visning"},
    {TextId::ShowOriginalAndResult, "Vis original- og resultatvisning."},
    {TextId::ShowOnlyResult, "Vis kun resultatvisningen."},
    {TextId::StackViews, "Stabl visninger"},
    {TextId::SideBySide, "Side om side"},
    {TextId::Pixelize, "Pixelér"},
    {TextId::PixelSize, "Pixelstørrelse"},
    {TextId::BlockSample, "Blokprøve"},
    {TextId::Average, "Gennemsnit"},
    {TextId::Weighted, "Vægtet"},
    {TextId::UsePalette, "Brug palette"},
    {TextId::PreserveTransparency, "Bevar gennemsigtighed"},
    {TextId::NoPalettesSaved, "Ingen paletter gemt."},
    {TextId::UnsavedPalette, "Ugemt palette"},
    {TextId::Palette, "Palette"},
    {TextId::NewPalette, "Ny palette"},
    {TextId::Save, "Gem"},
    {TextId::SaveNew, "Gem ny"},
    {TextId::DeletePalette, "Slet palette"},
    {TextId::PaletteCountFormat, "%zu / %zu farver"},
    {TextId::AddColorToBegin, "Tilføj en farve for at begynde."},
    {TextId::EditColorFormat, "Rediger farve {index}"},
    {TextId::AddColor, "Tilføj farve"},
    {TextId::MaxColors, "Maks. farver"},
    {TextId::ColorLevels, "Farveniveauer"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Tilstand"},
    {TextId::None, "Ingen"},
    {TextId::Pattern, "Mønster"},
    {TextId::Amount, "Mængde"},
    {TextId::Adjustments, "Justeringer"},
    {TextId::Brightness, "Lysstyrke"},
    {TextId::Contrast, "Kontrast"},
    {TextId::Saturation, "Mætning"},
    {TextId::InputBlack, "Input-sort"},
    {TextId::InputWhite, "Input-hvid"},
    {TextId::OutputBlack, "Output-sort"},
    {TextId::OutputWhite, "Output-hvid"},
    {TextId::Tint, "Tone"},
    {TextId::TintStrength, "Tonestyrke"},
    {TextId::ResetAdjustments, "Nulstil justeringer"},
    {TextId::Result, "Resultat"},
    {TextId::Original, "Original"},
    {TextId::Fit, "Tilpas"},
    {TextId::NoImageLoaded, "Intet billede indlæst"},
    {TextId::Value, "Værdi"},
    {TextId::Apply, "Anvend"},
    {TextId::Cancel, "Annuller"},
    {TextId::Open, "Åbn"},
    {TextId::Delete, "Slet"},
    {TextId::Overwrite, "Overskriv"},
    {TextId::KeepBoth, "Behold begge"},
    {TextId::PaletteName, "Palettenavn"},
    {TextId::Add, "Tilføj"},
    {TextId::DeleteColor, "Slet farve"},
    {TextId::ImagesFilter, "Billeder"},
    {TextId::AllFilesFilter, "Alle filer"},
    {TextId::PngImageFilter, "PNG-billede"},
    {TextId::StatusOpenImageToBegin, "Åbn et billede for at begynde."},
    {TextId::StatusPreviewUpdatedFormat, "Forhåndsvisning opdateret på {ms} ms."},
    {TextId::StatusLoadedFormat, "{name} indlæst."},
    {TextId::StatusImportedPaletteFormat, "Palette {name} importeret."},
    {TextId::StatusSavedPaletteFormat, "Palette {name} gemt."},
    {TextId::StatusDeletedPaletteFormat, "Palette {name} slettet."},
    {TextId::StatusExportedFormat, "{name} eksporteret."},
    {TextId::StatusLanguageChangedFormat, "Sprog ændret til {language}."},
};

constexpr Translation kSwedish[] = {
    {TextId::LanguageWindowTitle, "Språk"},
    {TextId::ChooseLanguage, "Välj ett språk"},
    {TextId::AboutWindowTitle, "Om Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Om Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer av Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Släppt under MIT-licensen."},
    {TextId::AboutThirdPartyTitle, "Tredjepartslicenser och erkännanden"},
    {TextId::AboutDependenciesTitle, "Beroenden"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 från libsdl-org/SDL, under zlib-licensen."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 från ocornut/imgui, under MIT-licensen."},
    {TextId::AboutDependencyStb, "stb vid commit 31c1ad37456438565541f4919958214b6e762fb4 från nothings/stb, med dubbel licens public domain/MIT."},
    {TextId::AboutPalettesTitle, "Medföljande paletter"},
    {TextId::AboutPalettesCredit, "Standardpalettfilerna är hämtade från Lospec. Länkar till de ursprungliga palettsidorna finns i THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "README-skärmbilden och ikonfilerna är ursprungliga projektresurser."},
    {TextId::Close, "Stäng"},
    {TextId::OpenImage, "Öppna bild"},
    {TextId::ImportPalette, "Importera palett"},
    {TextId::ExportPng, "Exportera PNG"},
    {TextId::TwoViews, "Två vyer"},
    {TextId::OneView, "En vy"},
    {TextId::StackViews, "Stapla vyer"},
    {TextId::SideBySide, "Sida vid sida"},
    {TextId::Pixelize, "Pixla"},
    {TextId::PixelSize, "Pixelstorlek"},
    {TextId::BlockSample, "Blockprov"},
    {TextId::Average, "Medel"},
    {TextId::Weighted, "Viktad"},
    {TextId::UsePalette, "Använd palett"},
    {TextId::PreserveTransparency, "Bevara transparens"},
    {TextId::NoPalettesSaved, "Inga paletter sparade."},
    {TextId::UnsavedPalette, "Osparad palett"},
    {TextId::Palette, "Palett"},
    {TextId::NewPalette, "Ny palett"},
    {TextId::Save, "Spara"},
    {TextId::SaveNew, "Spara ny"},
    {TextId::DeletePalette, "Ta bort palett"},
    {TextId::PaletteCountFormat, "%zu / %zu färger"},
    {TextId::AddColorToBegin, "Lägg till en färg för att börja."},
    {TextId::EditColorFormat, "Redigera färg {index}"},
    {TextId::AddColor, "Lägg till färg"},
    {TextId::MaxColors, "Max färger"},
    {TextId::ColorLevels, "Färgnivåer"},
    {TextId::Dithering, "Rastrering"},
    {TextId::Mode, "Läge"},
    {TextId::None, "Ingen"},
    {TextId::Pattern, "Mönster"},
    {TextId::Amount, "Mängd"},
    {TextId::Adjustments, "Justeringar"},
    {TextId::Brightness, "Ljusstyrka"},
    {TextId::Contrast, "Kontrast"},
    {TextId::Saturation, "Mättnad"},
    {TextId::InputBlack, "Ingångssvart"},
    {TextId::InputWhite, "Ingångsvitt"},
    {TextId::OutputBlack, "Utgångssvart"},
    {TextId::OutputWhite, "Utgångsvitt"},
    {TextId::Tint, "Toning"},
    {TextId::TintStrength, "Toningsstyrka"},
    {TextId::ResetAdjustments, "Återställ justeringar"},
    {TextId::Result, "Resultat"},
    {TextId::Original, "Original"},
    {TextId::Fit, "Anpassa"},
    {TextId::NoImageLoaded, "Ingen bild inläst"},
    {TextId::Value, "Värde"},
    {TextId::Apply, "Använd"},
    {TextId::Cancel, "Avbryt"},
    {TextId::Open, "Öppna"},
    {TextId::Delete, "Ta bort"},
    {TextId::Overwrite, "Skriv över"},
    {TextId::KeepBoth, "Behåll båda"},
    {TextId::PaletteName, "Palettnamn"},
    {TextId::Add, "Lägg till"},
    {TextId::DeleteColor, "Ta bort färg"},
    {TextId::ImagesFilter, "Bilder"},
    {TextId::AllFilesFilter, "Alla filer"},
    {TextId::PngImageFilter, "PNG-bild"},
    {TextId::StatusOpenImageToBegin, "Öppna en bild för att börja."},
    {TextId::StatusPreviewUpdatedFormat, "Förhandsvisning uppdaterad på {ms} ms."},
    {TextId::StatusLoadedFormat, "{name} inläst."},
    {TextId::StatusImportedPaletteFormat, "Palett {name} importerad."},
    {TextId::StatusSavedPaletteFormat, "Palett {name} sparad."},
    {TextId::StatusDeletedPaletteFormat, "Palett {name} borttagen."},
    {TextId::StatusExportedFormat, "{name} exporterad."},
    {TextId::StatusLanguageChangedFormat, "Språk ändrat till {language}."},
};

constexpr Translation kNorwegian[] = {
    {TextId::LanguageWindowTitle, "Språk"},
    {TextId::ChooseLanguage, "Velg språk"},
    {TextId::AboutWindowTitle, "Om Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Om Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer av Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Utgitt under MIT-lisensen."},
    {TextId::AboutThirdPartyTitle, "Tredjepartslisenser og krediteringer"},
    {TextId::AboutDependenciesTitle, "Avhengigheter"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 fra libsdl-org/SDL, under zlib-lisensen."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 fra ocornut/imgui, under MIT-lisensen."},
    {TextId::AboutDependencyStb, "stb ved commit 31c1ad37456438565541f4919958214b6e762fb4 fra nothings/stb, med public-domain/MIT-dobbellisens."},
    {TextId::AboutPalettesTitle, "Medfølgende paletter"},
    {TextId::AboutPalettesCredit, "Standardpalettfilene er pakket med fra Lospec. Lenker til de opprinnelige palettsidene finnes i THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "README-skjermbildet og ikonfilene er originale prosjektressurser."},
    {TextId::Close, "Lukk"},
    {TextId::OpenImage, "Åpne bilde"},
    {TextId::ImportPalette, "Importer palett"},
    {TextId::ExportPng, "Eksporter PNG"},
    {TextId::TwoViews, "To visninger"},
    {TextId::OneView, "Én visning"},
    {TextId::StackViews, "Stable visninger"},
    {TextId::SideBySide, "Side om side"},
    {TextId::Pixelize, "Pikseler"},
    {TextId::PixelSize, "Pikselstørrelse"},
    {TextId::BlockSample, "Blokkprøve"},
    {TextId::Average, "Gjennomsnitt"},
    {TextId::Weighted, "Vektet"},
    {TextId::UsePalette, "Bruk palett"},
    {TextId::PreserveTransparency, "Bevar gjennomsiktighet"},
    {TextId::NoPalettesSaved, "Ingen paletter lagret."},
    {TextId::UnsavedPalette, "Ulagret palett"},
    {TextId::Palette, "Palett"},
    {TextId::NewPalette, "Ny palett"},
    {TextId::Save, "Lagre"},
    {TextId::SaveNew, "Lagre ny"},
    {TextId::DeletePalette, "Slett palett"},
    {TextId::PaletteCountFormat, "%zu / %zu farger"},
    {TextId::AddColorToBegin, "Legg til en farge for å begynne."},
    {TextId::EditColorFormat, "Rediger farge {index}"},
    {TextId::AddColor, "Legg til farge"},
    {TextId::MaxColors, "Maks farger"},
    {TextId::ColorLevels, "Fargenivåer"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Modus"},
    {TextId::None, "Ingen"},
    {TextId::Pattern, "Mønster"},
    {TextId::Amount, "Mengde"},
    {TextId::Adjustments, "Justeringer"},
    {TextId::Brightness, "Lysstyrke"},
    {TextId::Contrast, "Kontrast"},
    {TextId::Saturation, "Metning"},
    {TextId::InputBlack, "Inngangssvart"},
    {TextId::InputWhite, "Inngangshvitt"},
    {TextId::OutputBlack, "Utgangssvart"},
    {TextId::OutputWhite, "Utgangshvitt"},
    {TextId::Tint, "Fargetone"},
    {TextId::TintStrength, "Tonestyrke"},
    {TextId::ResetAdjustments, "Tilbakestill justeringer"},
    {TextId::Result, "Resultat"},
    {TextId::Original, "Original"},
    {TextId::Fit, "Tilpass"},
    {TextId::NoImageLoaded, "Ingen bilder lastet"},
    {TextId::Value, "Verdi"},
    {TextId::Apply, "Bruk"},
    {TextId::Cancel, "Avbryt"},
    {TextId::Open, "Åpne"},
    {TextId::Delete, "Slett"},
    {TextId::Overwrite, "Overskriv"},
    {TextId::KeepBoth, "Behold begge"},
    {TextId::PaletteName, "Palettnavn"},
    {TextId::Add, "Legg til"},
    {TextId::DeleteColor, "Slett farge"},
    {TextId::ImagesFilter, "Bilder"},
    {TextId::AllFilesFilter, "Alle filer"},
    {TextId::PngImageFilter, "PNG-bilde"},
    {TextId::StatusOpenImageToBegin, "Åpne et bilde for å begynne."},
    {TextId::StatusPreviewUpdatedFormat, "Forhåndsvisning oppdatert på {ms} ms."},
    {TextId::StatusLoadedFormat, "{name} lastet."},
    {TextId::StatusImportedPaletteFormat, "Palett {name} importert."},
    {TextId::StatusSavedPaletteFormat, "Palett {name} lagret."},
    {TextId::StatusDeletedPaletteFormat, "Palett {name} slettet."},
    {TextId::StatusExportedFormat, "{name} eksportert."},
    {TextId::StatusLanguageChangedFormat, "Språk endret til {language}."},
};

constexpr Translation kCzech[] = {
    {TextId::LanguageWindowTitle, "Jazyk"},
    {TextId::ChooseLanguage, "Vyberte jazyk"},
    {TextId::AboutWindowTitle, "O Pixelizeru"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "O Pixelizeru"},
    {TextId::AboutProjectCredit, "Pixelizer od Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Vydáno pod licencí MIT."},
    {TextId::AboutThirdPartyTitle, "Licence a kredity třetích stran"},
    {TextId::AboutDependenciesTitle, "Závislosti"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 od libsdl-org/SDL, pod licencí zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 od ocornut/imgui, pod licencí MIT."},
    {TextId::AboutDependencyStb, "stb na commitu 31c1ad37456438565541f4919958214b6e762fb4 od nothings/stb, s dvojí licencí public-domain/MIT."},
    {TextId::AboutPalettesTitle, "Přibalené palety"},
    {TextId::AboutPalettesCredit, "Výchozí soubory palet jsou přibaleny z Lospec. Odkazy na původní stránky palet jsou v THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Snímek v README a soubory ikon jsou původní projektové prostředky."},
    {TextId::Close, "Zavřít"},
    {TextId::OpenImage, "Otevřít obrázek"},
    {TextId::ImportPalette, "Importovat paletu"},
    {TextId::ExportPng, "Exportovat PNG"},
    {TextId::TwoViews, "Dva pohledy"},
    {TextId::OneView, "Jeden pohled"},
    {TextId::StackViews, "Skládat pohledy"},
    {TextId::SideBySide, "Vedle sebe"},
    {TextId::Pixelize, "Pixelizovat"},
    {TextId::PixelSize, "Velikost pixelu"},
    {TextId::BlockSample, "Vzorek bloku"},
    {TextId::Average, "Průměr"},
    {TextId::Weighted, "Vážený"},
    {TextId::UsePalette, "Použít paletu"},
    {TextId::PreserveTransparency, "Zachovat průhlednost"},
    {TextId::NoPalettesSaved, "Žádné uložené palety."},
    {TextId::UnsavedPalette, "Neuložená paleta"},
    {TextId::Palette, "Paleta"},
    {TextId::NewPalette, "Nová paleta"},
    {TextId::Save, "Uložit"},
    {TextId::SaveNew, "Uložit novou"},
    {TextId::DeletePalette, "Smazat paletu"},
    {TextId::PaletteCountFormat, "%zu / %zu barev"},
    {TextId::AddColorToBegin, "Začněte přidáním barvy."},
    {TextId::EditColorFormat, "Upravit barvu {index}"},
    {TextId::AddColor, "Přidat barvu"},
    {TextId::MaxColors, "Max. barev"},
    {TextId::ColorLevels, "Úrovně barev"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Režim"},
    {TextId::None, "Žádný"},
    {TextId::Pattern, "Vzor"},
    {TextId::Amount, "Množství"},
    {TextId::Adjustments, "Úpravy"},
    {TextId::Brightness, "Jas"},
    {TextId::Contrast, "Kontrast"},
    {TextId::Saturation, "Sytost"},
    {TextId::InputBlack, "Vstupní černá"},
    {TextId::InputWhite, "Vstupní bílá"},
    {TextId::OutputBlack, "Výstupní černá"},
    {TextId::OutputWhite, "Výstupní bílá"},
    {TextId::Tint, "Odstín"},
    {TextId::TintStrength, "Síla odstínu"},
    {TextId::ResetAdjustments, "Obnovit úpravy"},
    {TextId::Result, "Výsledek"},
    {TextId::Original, "Originál"},
    {TextId::Fit, "Přizpůsobit"},
    {TextId::NoImageLoaded, "Není načten žádný obrázek"},
    {TextId::Value, "Hodnota"},
    {TextId::Apply, "Použít"},
    {TextId::Cancel, "Zrušit"},
    {TextId::Open, "Otevřít"},
    {TextId::Delete, "Smazat"},
    {TextId::Overwrite, "Přepsat"},
    {TextId::KeepBoth, "Ponechat obě"},
    {TextId::PaletteName, "Název palety"},
    {TextId::Add, "Přidat"},
    {TextId::DeleteColor, "Smazat barvu"},
    {TextId::ImagesFilter, "Obrázky"},
    {TextId::AllFilesFilter, "Všechny soubory"},
    {TextId::PngImageFilter, "Obrázek PNG"},
    {TextId::StatusOpenImageToBegin, "Začněte otevřením obrázku."},
    {TextId::StatusPreviewUpdatedFormat, "Náhled aktualizován za {ms} ms."},
    {TextId::StatusLoadedFormat, "{name} načten."},
    {TextId::StatusImportedPaletteFormat, "Paleta {name} importována."},
    {TextId::StatusSavedPaletteFormat, "Paleta {name} uložena."},
    {TextId::StatusDeletedPaletteFormat, "Paleta {name} smazána."},
    {TextId::StatusExportedFormat, "{name} exportován."},
    {TextId::StatusLanguageChangedFormat, "Jazyk změněn na {language}."},
};

constexpr Translation kItalian[] = {
    {TextId::LanguageWindowTitle, "Lingua"},
    {TextId::ChooseLanguage, "Scegli una lingua"},
    {TextId::AboutWindowTitle, "Informazioni su Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Informazioni su Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer di Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Rilasciato con licenza MIT."},
    {TextId::AboutThirdPartyTitle, "Licenze e crediti di terze parti"},
    {TextId::AboutDependenciesTitle, "Dipendenze"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 da libsdl-org/SDL, con licenza zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 da ocornut/imgui, con licenza MIT."},
    {TextId::AboutDependencyStb, "stb al commit 31c1ad37456438565541f4919958214b6e762fb4 da nothings/stb, con doppia licenza public-domain/MIT."},
    {TextId::AboutPalettesTitle, "Palette incluse"},
    {TextId::AboutPalettesCredit, "I file delle palette predefinite sono inclusi da Lospec. I link alle pagine originali delle palette sono elencati in THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Lo screenshot nel README e i file delle icone sono risorse originali del progetto."},
    {TextId::Close, "Chiudi"},
    {TextId::OpenImage, "Apri immagine"},
    {TextId::ImportPalette, "Importa palette"},
    {TextId::ExportPng, "Esporta PNG"},
    {TextId::TwoViews, "Due viste"},
    {TextId::OneView, "Una vista"},
    {TextId::StackViews, "Impila viste"},
    {TextId::SideBySide, "Affiancate"},
    {TextId::Pixelize, "Pixelizza"},
    {TextId::PixelSize, "Dimensione pixel"},
    {TextId::BlockSample, "Campione blocco"},
    {TextId::Average, "Media"},
    {TextId::Weighted, "Ponderato"},
    {TextId::UsePalette, "Usa palette"},
    {TextId::PreserveTransparency, "Mantieni trasparenza"},
    {TextId::NoPalettesSaved, "Nessuna palette salvata."},
    {TextId::UnsavedPalette, "Palette non salvata"},
    {TextId::Palette, "Palette"},
    {TextId::NewPalette, "Nuova palette"},
    {TextId::Save, "Salva"},
    {TextId::SaveNew, "Salva nuova"},
    {TextId::DeletePalette, "Elimina palette"},
    {TextId::PaletteCountFormat, "%zu / %zu colori"},
    {TextId::AddColorToBegin, "Aggiungi un colore per iniziare."},
    {TextId::EditColorFormat, "Modifica colore {index}"},
    {TextId::AddColor, "Aggiungi colore"},
    {TextId::MaxColors, "Colori max"},
    {TextId::ColorLevels, "Livelli colore"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Modalità"},
    {TextId::None, "Nessuno"},
    {TextId::Pattern, "Motivo"},
    {TextId::Amount, "Quantità"},
    {TextId::Adjustments, "Regolazioni"},
    {TextId::Brightness, "Luminosità"},
    {TextId::Contrast, "Contrasto"},
    {TextId::Saturation, "Saturazione"},
    {TextId::InputBlack, "Nero in ingresso"},
    {TextId::InputWhite, "Bianco in ingresso"},
    {TextId::OutputBlack, "Nero in uscita"},
    {TextId::OutputWhite, "Bianco in uscita"},
    {TextId::Tint, "Tinta"},
    {TextId::TintStrength, "Intensità tinta"},
    {TextId::ResetAdjustments, "Reimposta regolazioni"},
    {TextId::Result, "Risultato"},
    {TextId::Original, "Originale"},
    {TextId::Fit, "Adatta"},
    {TextId::NoImageLoaded, "Nessuna immagine caricata"},
    {TextId::Value, "Valore"},
    {TextId::Apply, "Applica"},
    {TextId::Cancel, "Annulla"},
    {TextId::Open, "Apri"},
    {TextId::Delete, "Elimina"},
    {TextId::Overwrite, "Sovrascrivi"},
    {TextId::KeepBoth, "Mantieni entrambe"},
    {TextId::PaletteName, "Nome palette"},
    {TextId::Add, "Aggiungi"},
    {TextId::DeleteColor, "Elimina colore"},
    {TextId::ImagesFilter, "Immagini"},
    {TextId::AllFilesFilter, "Tutti i file"},
    {TextId::PngImageFilter, "Immagine PNG"},
    {TextId::StatusOpenImageToBegin, "Apri un'immagine per iniziare."},
    {TextId::StatusPreviewUpdatedFormat, "Anteprima aggiornata in {ms} ms."},
    {TextId::StatusLoadedFormat, "{name} caricata."},
    {TextId::StatusImportedPaletteFormat, "Palette {name} importata."},
    {TextId::StatusSavedPaletteFormat, "Palette {name} salvata."},
    {TextId::StatusDeletedPaletteFormat, "Palette {name} eliminata."},
    {TextId::StatusExportedFormat, "{name} esportato."},
    {TextId::StatusLanguageChangedFormat, "Lingua cambiata in {language}."},
};

constexpr Translation kGreek[] = {
    {TextId::LanguageWindowTitle, "Γλώσσα"},
    {TextId::ChooseLanguage, "Επιλέξτε γλώσσα"},
    {TextId::AboutWindowTitle, "Σχετικά με το Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Σχετικά με το Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer από τον Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Κυκλοφορεί με άδεια MIT."},
    {TextId::AboutThirdPartyTitle, "Άδειες και αναφορές τρίτων"},
    {TextId::AboutDependenciesTitle, "Εξαρτήσεις"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 από libsdl-org/SDL, με άδεια zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 από ocornut/imgui, με άδεια MIT."},
    {TextId::AboutDependencyStb, "stb στο commit 31c1ad37456438565541f4919958214b6e762fb4 από nothings/stb, με διπλή άδεια public-domain/MIT."},
    {TextId::AboutPalettesTitle, "Ενσωματωμένες παλέτες"},
    {TextId::AboutPalettesCredit, "Τα προεπιλεγμένα αρχεία παλετών περιλαμβάνονται από το Lospec. Οι σύνδεσμοι στις αρχικές σελίδες παλετών βρίσκονται στο THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Το στιγμιότυπο του README και τα αρχεία εικονιδίων είναι πρωτότυπα στοιχεία του έργου."},
    {TextId::Close, "Κλείσιμο"},
    {TextId::OpenImage, "Άνοιγμα εικόνας"},
    {TextId::ImportPalette, "Εισαγωγή παλέτας"},
    {TextId::ExportPng, "Εξαγωγή PNG"},
    {TextId::TwoViews, "Δύο προβολές"},
    {TextId::OneView, "Μία προβολή"},
    {TextId::Pixelize, "Pixelize"},
    {TextId::PixelSize, "Μέγεθος pixel"},
    {TextId::BlockSample, "Δείγμα μπλοκ"},
    {TextId::Average, "Μέσος όρος"},
    {TextId::Weighted, "Σταθμισμένο"},
    {TextId::UsePalette, "Χρήση παλέτας"},
    {TextId::PreserveTransparency, "Διατήρηση διαφάνειας"},
    {TextId::NoPalettesSaved, "Δεν υπάρχουν αποθηκευμένες παλέτες."},
    {TextId::UnsavedPalette, "Μη αποθηκευμένη παλέτα"},
    {TextId::Palette, "Παλέτα"},
    {TextId::NewPalette, "Νέα παλέτα"},
    {TextId::Save, "Αποθήκευση"},
    {TextId::SaveNew, "Αποθήκευση νέας"},
    {TextId::DeletePalette, "Διαγραφή παλέτας"},
    {TextId::PaletteCountFormat, "%zu / %zu χρώματα"},
    {TextId::AddColorToBegin, "Προσθέστε ένα χρώμα για να ξεκινήσετε."},
    {TextId::AddColor, "Προσθήκη χρώματος"},
    {TextId::MaxColors, "Μέγιστα χρώματα"},
    {TextId::ColorLevels, "Επίπεδα χρώματος"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Λειτουργία"},
    {TextId::None, "Κανένα"},
    {TextId::Pattern, "Μοτίβο"},
    {TextId::Amount, "Ποσότητα"},
    {TextId::Adjustments, "Ρυθμίσεις"},
    {TextId::Brightness, "Φωτεινότητα"},
    {TextId::Contrast, "Αντίθεση"},
    {TextId::Saturation, "Κορεσμός"},
    {TextId::Tint, "Απόχρωση"},
    {TextId::TintStrength, "Ένταση απόχρωσης"},
    {TextId::ResetAdjustments, "Επαναφορά ρυθμίσεων"},
    {TextId::Result, "Αποτέλεσμα"},
    {TextId::Original, "Πρωτότυπο"},
    {TextId::Fit, "Προσαρμογή"},
    {TextId::NoImageLoaded, "Δεν έχει φορτωθεί εικόνα"},
    {TextId::Value, "Τιμή"},
    {TextId::Apply, "Εφαρμογή"},
    {TextId::Cancel, "Άκυρο"},
    {TextId::Open, "Άνοιγμα"},
    {TextId::Delete, "Διαγραφή"},
    {TextId::Overwrite, "Αντικατάσταση"},
    {TextId::KeepBoth, "Κράτηση και των δύο"},
    {TextId::PaletteName, "Όνομα παλέτας"},
    {TextId::Add, "Προσθήκη"},
    {TextId::DeleteColor, "Διαγραφή χρώματος"},
    {TextId::ImagesFilter, "Εικόνες"},
    {TextId::AllFilesFilter, "Όλα τα αρχεία"},
    {TextId::PngImageFilter, "Εικόνα PNG"},
    {TextId::StatusOpenImageToBegin, "Ανοίξτε μια εικόνα για να ξεκινήσετε."},
    {TextId::StatusPreviewUpdatedFormat, "Η προεπισκόπηση ενημερώθηκε σε {ms} ms."},
    {TextId::StatusLanguageChangedFormat, "Η γλώσσα άλλαξε σε {language}."},
};

constexpr Translation kPolish[] = {
    {TextId::LanguageWindowTitle, "Język"},
    {TextId::ChooseLanguage, "Wybierz język"},
    {TextId::AboutWindowTitle, "O Pixelizerze"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "O Pixelizerze"},
    {TextId::AboutProjectCredit, "Pixelizer autorstwa Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Wydany na licencji MIT."},
    {TextId::AboutThirdPartyTitle, "Licencje i podziękowania stron trzecich"},
    {TextId::AboutDependenciesTitle, "Zależności"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 od libsdl-org/SDL, na licencji zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 od ocornut/imgui, na licencji MIT."},
    {TextId::AboutDependencyStb, "stb w commicie 31c1ad37456438565541f4919958214b6e762fb4 od nothings/stb, na podwójnej licencji public-domain/MIT."},
    {TextId::AboutPalettesTitle, "Dołączone palety"},
    {TextId::AboutPalettesCredit, "Domyślne pliki palet pochodzą z Lospec. Linki do oryginalnych stron palet są wymienione w THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Zrzut ekranu w README i pliki ikon są oryginalnymi zasobami projektu."},
    {TextId::Close, "Zamknij"},
    {TextId::OpenImage, "Otwórz obraz"},
    {TextId::ImportPalette, "Importuj paletę"},
    {TextId::ExportPng, "Eksportuj PNG"},
    {TextId::TwoViews, "Dwa widoki"},
    {TextId::OneView, "Jeden widok"},
    {TextId::StackViews, "Ułóż widoki"},
    {TextId::SideBySide, "Obok siebie"},
    {TextId::Pixelize, "Pikselizuj"},
    {TextId::PixelSize, "Rozmiar piksela"},
    {TextId::BlockSample, "Próbka bloku"},
    {TextId::Average, "Średnia"},
    {TextId::Weighted, "Ważona"},
    {TextId::UsePalette, "Użyj palety"},
    {TextId::PreserveTransparency, "Zachowaj przezroczystość"},
    {TextId::NoPalettesSaved, "Brak zapisanych palet."},
    {TextId::UnsavedPalette, "Niezapisana paleta"},
    {TextId::Palette, "Paleta"},
    {TextId::NewPalette, "Nowa paleta"},
    {TextId::Save, "Zapisz"},
    {TextId::SaveNew, "Zapisz nową"},
    {TextId::DeletePalette, "Usuń paletę"},
    {TextId::PaletteCountFormat, "%zu / %zu kolorów"},
    {TextId::AddColorToBegin, "Dodaj kolor, aby rozpocząć."},
    {TextId::AddColor, "Dodaj kolor"},
    {TextId::MaxColors, "Maks. kolorów"},
    {TextId::ColorLevels, "Poziomy kolorów"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Tryb"},
    {TextId::None, "Brak"},
    {TextId::Pattern, "Wzór"},
    {TextId::Amount, "Ilość"},
    {TextId::Adjustments, "Korekty"},
    {TextId::Brightness, "Jasność"},
    {TextId::Contrast, "Kontrast"},
    {TextId::Saturation, "Nasycenie"},
    {TextId::InputBlack, "Czerń wejściowa"},
    {TextId::InputWhite, "Biel wejściowa"},
    {TextId::OutputBlack, "Czerń wyjściowa"},
    {TextId::OutputWhite, "Biel wyjściowa"},
    {TextId::Tint, "Odcień"},
    {TextId::TintStrength, "Siła odcienia"},
    {TextId::ResetAdjustments, "Resetuj korekty"},
    {TextId::Result, "Wynik"},
    {TextId::Original, "Oryginał"},
    {TextId::Fit, "Dopasuj"},
    {TextId::NoImageLoaded, "Nie wczytano obrazu"},
    {TextId::Value, "Wartość"},
    {TextId::Apply, "Zastosuj"},
    {TextId::Cancel, "Anuluj"},
    {TextId::Open, "Otwórz"},
    {TextId::Delete, "Usuń"},
    {TextId::Overwrite, "Zastąp"},
    {TextId::KeepBoth, "Zachowaj obie"},
    {TextId::PaletteName, "Nazwa palety"},
    {TextId::Add, "Dodaj"},
    {TextId::DeleteColor, "Usuń kolor"},
    {TextId::ImagesFilter, "Obrazy"},
    {TextId::AllFilesFilter, "Wszystkie pliki"},
    {TextId::PngImageFilter, "Obraz PNG"},
    {TextId::StatusOpenImageToBegin, "Otwórz obraz, aby rozpocząć."},
    {TextId::StatusPreviewUpdatedFormat, "Podgląd zaktualizowano w {ms} ms."},
    {TextId::StatusLanguageChangedFormat, "Zmieniono język na {language}."},
};

constexpr Translation kFinnish[] = {
    {TextId::LanguageWindowTitle, "Kieli"},
    {TextId::ChooseLanguage, "Valitse kieli"},
    {TextId::AboutWindowTitle, "Tietoja Pixelizeristä"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Tietoja Pixelizeristä"},
    {TextId::AboutProjectCredit, "Pixelizer, tekijä Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Julkaistu MIT-lisenssillä."},
    {TextId::AboutThirdPartyTitle, "Kolmansien osapuolten lisenssit ja krediitit"},
    {TextId::AboutDependenciesTitle, "Riippuvuudet"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 kohteesta libsdl-org/SDL, zlib-lisenssillä."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 kohteesta ocornut/imgui, MIT-lisenssillä."},
    {TextId::AboutDependencyStb, "stb commitissa 31c1ad37456438565541f4919958214b6e762fb4 kohteesta nothings/stb, public-domain/MIT-kaksoislisenssillä."},
    {TextId::AboutPalettesTitle, "Mukana olevat paletit"},
    {TextId::AboutPalettesCredit, "Oletuspalettitiedostot on koottu Lospecista. Linkit alkuperäisille palettisivuille on lueteltu tiedostossa THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "README-kuvakaappaus ja ikonitiedostot ovat projektin alkuperäisiä resursseja."},
    {TextId::Close, "Sulje"},
    {TextId::OpenImage, "Avaa kuva"},
    {TextId::ImportPalette, "Tuo paletti"},
    {TextId::ExportPng, "Vie PNG"},
    {TextId::TwoViews, "Kaksi näkymää"},
    {TextId::OneView, "Yksi näkymä"},
    {TextId::StackViews, "Pinoa näkymät"},
    {TextId::SideBySide, "Vierekkäin"},
    {TextId::Pixelize, "Pikselöi"},
    {TextId::PixelSize, "Pikselikoko"},
    {TextId::BlockSample, "Lohkonäyte"},
    {TextId::Average, "Keskiarvo"},
    {TextId::Weighted, "Painotettu"},
    {TextId::UsePalette, "Käytä palettia"},
    {TextId::PreserveTransparency, "Säilytä läpinäkyvyys"},
    {TextId::NoPalettesSaved, "Ei tallennettuja paletteja."},
    {TextId::UnsavedPalette, "Tallentamaton paletti"},
    {TextId::Palette, "Paletti"},
    {TextId::NewPalette, "Uusi paletti"},
    {TextId::Save, "Tallenna"},
    {TextId::SaveNew, "Tallenna uusi"},
    {TextId::DeletePalette, "Poista paletti"},
    {TextId::PaletteCountFormat, "%zu / %zu väriä"},
    {TextId::AddColorToBegin, "Lisää väri aloittaaksesi."},
    {TextId::AddColor, "Lisää väri"},
    {TextId::MaxColors, "Värejä enintään"},
    {TextId::ColorLevels, "Väritasot"},
    {TextId::Dithering, "Dithering"},
    {TextId::Mode, "Tila"},
    {TextId::None, "Ei mitään"},
    {TextId::Pattern, "Kuvio"},
    {TextId::Amount, "Määrä"},
    {TextId::Adjustments, "Säädöt"},
    {TextId::Brightness, "Kirkkaus"},
    {TextId::Contrast, "Kontrasti"},
    {TextId::Saturation, "Kylläisyys"},
    {TextId::InputBlack, "Syötteen musta"},
    {TextId::InputWhite, "Syötteen valkoinen"},
    {TextId::OutputBlack, "Tulosteen musta"},
    {TextId::OutputWhite, "Tulosteen valkoinen"},
    {TextId::Tint, "Sävy"},
    {TextId::TintStrength, "Sävyn vahvuus"},
    {TextId::ResetAdjustments, "Palauta säädöt"},
    {TextId::Result, "Tulos"},
    {TextId::Original, "Alkuperäinen"},
    {TextId::Fit, "Sovita"},
    {TextId::NoImageLoaded, "Kuvaa ei ladattu"},
    {TextId::Value, "Arvo"},
    {TextId::Apply, "Käytä"},
    {TextId::Cancel, "Peruuta"},
    {TextId::Open, "Avaa"},
    {TextId::Delete, "Poista"},
    {TextId::Overwrite, "Korvaa"},
    {TextId::KeepBoth, "Säilytä molemmat"},
    {TextId::PaletteName, "Paletin nimi"},
    {TextId::Add, "Lisää"},
    {TextId::DeleteColor, "Poista väri"},
    {TextId::ImagesFilter, "Kuvat"},
    {TextId::AllFilesFilter, "Kaikki tiedostot"},
    {TextId::PngImageFilter, "PNG-kuva"},
    {TextId::StatusOpenImageToBegin, "Avaa kuva aloittaaksesi."},
    {TextId::StatusPreviewUpdatedFormat, "Esikatselu päivitetty {ms} ms:ssa."},
    {TextId::StatusLanguageChangedFormat, "Kieleksi vaihdettiin {language}."},
};

constexpr Translation kUkrainian[] = {
    {TextId::LanguageWindowTitle, "Мова"},
    {TextId::ChooseLanguage, "Виберіть мову"},
    {TextId::AboutWindowTitle, "Про Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Про Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer від Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Випущено за ліцензією MIT."},
    {TextId::AboutThirdPartyTitle, "Ліцензії та подяки третім сторонам"},
    {TextId::AboutDependenciesTitle, "Залежності"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 від libsdl-org/SDL, за ліцензією zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 від ocornut/imgui, за ліцензією MIT."},
    {TextId::AboutDependencyStb, "stb на коміті 31c1ad37456438565541f4919958214b6e762fb4 від nothings/stb, з подвійною ліцензією public-domain/MIT."},
    {TextId::AboutPalettesTitle, "Вбудовані палітри"},
    {TextId::AboutPalettesCredit, "Типові файли палітр вбудовано з Lospec. Посилання на оригінальні сторінки палітр наведено в THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Знімок екрана в README та файли піктограм є оригінальними ресурсами проєкту."},
    {TextId::Close, "Закрити"},
    {TextId::OpenImage, "Відкрити зображення"},
    {TextId::ImportPalette, "Імпортувати палітру"},
    {TextId::ExportPng, "Експортувати PNG"},
    {TextId::TwoViews, "Два вигляди"},
    {TextId::OneView, "Один вигляд"},
    {TextId::Pixelize, "Пікселізувати"},
    {TextId::PixelSize, "Розмір пікселя"},
    {TextId::BlockSample, "Зразок блока"},
    {TextId::Average, "Середнє"},
    {TextId::Weighted, "Зважене"},
    {TextId::UsePalette, "Використовувати палітру"},
    {TextId::PreserveTransparency, "Зберігати прозорість"},
    {TextId::NoPalettesSaved, "Збережених палітр немає."},
    {TextId::UnsavedPalette, "Незбережена палітра"},
    {TextId::Palette, "Палітра"},
    {TextId::NewPalette, "Нова палітра"},
    {TextId::Save, "Зберегти"},
    {TextId::SaveNew, "Зберегти як нову"},
    {TextId::DeletePalette, "Видалити палітру"},
    {TextId::PaletteCountFormat, "%zu / %zu кольорів"},
    {TextId::AddColorToBegin, "Додайте колір, щоб почати."},
    {TextId::AddColor, "Додати колір"},
    {TextId::MaxColors, "Макс. кольорів"},
    {TextId::ColorLevels, "Рівні кольору"},
    {TextId::Dithering, "Дизеринг"},
    {TextId::Mode, "Режим"},
    {TextId::None, "Немає"},
    {TextId::Pattern, "Візерунок"},
    {TextId::Amount, "Кількість"},
    {TextId::Adjustments, "Налаштування"},
    {TextId::Brightness, "Яскравість"},
    {TextId::Contrast, "Контраст"},
    {TextId::Saturation, "Насиченість"},
    {TextId::Tint, "Відтінок"},
    {TextId::TintStrength, "Сила відтінку"},
    {TextId::ResetAdjustments, "Скинути налаштування"},
    {TextId::Result, "Результат"},
    {TextId::Original, "Оригінал"},
    {TextId::Fit, "Вмістити"},
    {TextId::NoImageLoaded, "Зображення не завантажено"},
    {TextId::Value, "Значення"},
    {TextId::Apply, "Застосувати"},
    {TextId::Cancel, "Скасувати"},
    {TextId::Open, "Відкрити"},
    {TextId::Delete, "Видалити"},
    {TextId::Overwrite, "Перезаписати"},
    {TextId::KeepBoth, "Залишити обидві"},
    {TextId::PaletteName, "Назва палітри"},
    {TextId::Add, "Додати"},
    {TextId::DeleteColor, "Видалити колір"},
    {TextId::ImagesFilter, "Зображення"},
    {TextId::AllFilesFilter, "Усі файли"},
    {TextId::PngImageFilter, "Зображення PNG"},
    {TextId::StatusOpenImageToBegin, "Відкрийте зображення, щоб почати."},
    {TextId::StatusPreviewUpdatedFormat, "Попередній перегляд оновлено за {ms} мс."},
    {TextId::StatusLanguageChangedFormat, "Мову змінено на {language}."},
};

constexpr Translation kRussian[] = {
    {TextId::LanguageWindowTitle, "Язык"},
    {TextId::ChooseLanguage, "Выберите язык"},
    {TextId::AboutWindowTitle, "О Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "О Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer от Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. Выпущено по лицензии MIT."},
    {TextId::AboutThirdPartyTitle, "Лицензии и благодарности третьим сторонам"},
    {TextId::AboutDependenciesTitle, "Зависимости"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 от libsdl-org/SDL, по лицензии zlib."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 от ocornut/imgui, по лицензии MIT."},
    {TextId::AboutDependencyStb, "stb на коммите 31c1ad37456438565541f4919958214b6e762fb4 от nothings/stb, с двойной лицензией public-domain/MIT."},
    {TextId::AboutPalettesTitle, "Встроенные палитры"},
    {TextId::AboutPalettesCredit, "Файлы палитр по умолчанию включены из Lospec. Ссылки на исходные страницы палитр перечислены в THIRD_PARTY.md."},
    {TextId::AboutAssetsCredit, "Снимок экрана в README и файлы значков являются оригинальными ресурсами проекта."},
    {TextId::Close, "Закрыть"},
    {TextId::OpenImage, "Открыть изображение"},
    {TextId::ImportPalette, "Импортировать палитру"},
    {TextId::ExportPng, "Экспорт PNG"},
    {TextId::TwoViews, "Два вида"},
    {TextId::OneView, "Один вид"},
    {TextId::Pixelize, "Пикселизировать"},
    {TextId::PixelSize, "Размер пикселя"},
    {TextId::BlockSample, "Образец блока"},
    {TextId::Average, "Среднее"},
    {TextId::Weighted, "Взвешенное"},
    {TextId::UsePalette, "Использовать палитру"},
    {TextId::PreserveTransparency, "Сохранять прозрачность"},
    {TextId::NoPalettesSaved, "Сохранённых палитр нет."},
    {TextId::UnsavedPalette, "Несохранённая палитра"},
    {TextId::Palette, "Палитра"},
    {TextId::NewPalette, "Новая палитра"},
    {TextId::Save, "Сохранить"},
    {TextId::SaveNew, "Сохранить новую"},
    {TextId::DeletePalette, "Удалить палитру"},
    {TextId::PaletteCountFormat, "%zu / %zu цветов"},
    {TextId::AddColorToBegin, "Добавьте цвет, чтобы начать."},
    {TextId::AddColor, "Добавить цвет"},
    {TextId::MaxColors, "Макс. цветов"},
    {TextId::ColorLevels, "Уровни цвета"},
    {TextId::Dithering, "Дизеринг"},
    {TextId::Mode, "Режим"},
    {TextId::None, "Нет"},
    {TextId::Pattern, "Узор"},
    {TextId::Amount, "Количество"},
    {TextId::Adjustments, "Настройки"},
    {TextId::Brightness, "Яркость"},
    {TextId::Contrast, "Контраст"},
    {TextId::Saturation, "Насыщенность"},
    {TextId::Tint, "Оттенок"},
    {TextId::TintStrength, "Сила оттенка"},
    {TextId::ResetAdjustments, "Сбросить настройки"},
    {TextId::Result, "Результат"},
    {TextId::Original, "Оригинал"},
    {TextId::Fit, "Вписать"},
    {TextId::NoImageLoaded, "Изображение не загружено"},
    {TextId::Value, "Значение"},
    {TextId::Apply, "Применить"},
    {TextId::Cancel, "Отмена"},
    {TextId::Open, "Открыть"},
    {TextId::Delete, "Удалить"},
    {TextId::Overwrite, "Перезаписать"},
    {TextId::KeepBoth, "Оставить обе"},
    {TextId::PaletteName, "Название палитры"},
    {TextId::Add, "Добавить"},
    {TextId::DeleteColor, "Удалить цвет"},
    {TextId::ImagesFilter, "Изображения"},
    {TextId::AllFilesFilter, "Все файлы"},
    {TextId::PngImageFilter, "Изображение PNG"},
    {TextId::StatusOpenImageToBegin, "Откройте изображение, чтобы начать."},
    {TextId::StatusPreviewUpdatedFormat, "Предпросмотр обновлён за {ms} мс."},
    {TextId::StatusLanguageChangedFormat, "Язык изменён на {language}."},
};

constexpr Translation kChineseSimplified[] = {
    {TextId::LanguageWindowTitle, "语言"},
    {TextId::ChooseLanguage, "选择语言"},
    {TextId::AboutWindowTitle, "关于 Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "关于 Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer 作者：Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo。根据 MIT 许可证发布。"},
    {TextId::AboutThirdPartyTitle, "第三方许可和鸣谢"},
    {TextId::AboutDependenciesTitle, "依赖项"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 来自 libsdl-org/SDL，采用 zlib 许可证。"},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 来自 ocornut/imgui，采用 MIT 许可证。"},
    {TextId::AboutDependencyStb, "stb 来自 nothings/stb，提交为 31c1ad37456438565541f4919958214b6e762fb4，采用公有领域/MIT 双许可证。"},
    {TextId::AboutPalettesTitle, "内置调色板"},
    {TextId::AboutPalettesCredit, "默认调色板文件来自 Lospec。原始调色板页面链接列在 THIRD_PARTY.md 中。"},
    {TextId::AboutAssetsCredit, "README 截图和图标文件是本项目的原创资源。"},
    {TextId::Close, "关闭"},
    {TextId::OpenImage, "打开图像"},
    {TextId::ImportPalette, "导入调色板"},
    {TextId::ExportPng, "导出 PNG"},
    {TextId::TwoViews, "双视图"},
    {TextId::OneView, "单视图"},
    {TextId::ShowOriginalAndResult, "显示原图和结果视图。"},
    {TextId::ShowOnlyResult, "只显示结果视图。"},
    {TextId::StackViews, "堆叠视图"},
    {TextId::SideBySide, "并排显示"},
    {TextId::ShowResultTop, "结果在上，原图在下。"},
    {TextId::ShowOriginalLeft, "原图在左，结果在右。"},
    {TextId::Pixelize, "像素化"},
    {TextId::PixelSize, "像素大小"},
    {TextId::BlockSample, "色块采样"},
    {TextId::Average, "平均"},
    {TextId::Weighted, "加权"},
    {TextId::UsePalette, "使用调色板"},
    {TextId::PreserveTransparency, "保留透明度"},
    {TextId::NoPalettesSaved, "没有已保存的调色板。"},
    {TextId::UnsavedPalette, "未保存的调色板"},
    {TextId::Palette, "调色板"},
    {TextId::NewPalette, "新建调色板"},
    {TextId::Save, "保存"},
    {TextId::SaveNew, "另存为新"},
    {TextId::DeletePalette, "删除调色板"},
    {TextId::PaletteCountFormat, "%zu / %zu 种颜色"},
    {TextId::AddColorToBegin, "添加一种颜色开始。"},
    {TextId::EditColorFormat, "编辑颜色 {index}"},
    {TextId::AddColor, "添加颜色"},
    {TextId::MaxColors, "最大颜色数"},
    {TextId::ColorLevels, "颜色级别"},
    {TextId::Dithering, "抖动"},
    {TextId::Mode, "模式"},
    {TextId::None, "无"},
    {TextId::Pattern, "图案"},
    {TextId::Amount, "数量"},
    {TextId::Adjustments, "调整"},
    {TextId::Brightness, "亮度"},
    {TextId::Contrast, "对比度"},
    {TextId::Gamma, "伽马"},
    {TextId::Saturation, "饱和度"},
    {TextId::InputBlack, "输入黑场"},
    {TextId::InputWhite, "输入白场"},
    {TextId::OutputBlack, "输出黑场"},
    {TextId::OutputWhite, "输出白场"},
    {TextId::Tint, "色调"},
    {TextId::TintStrength, "色调强度"},
    {TextId::ResetAdjustments, "重置调整"},
    {TextId::Result, "结果"},
    {TextId::Original, "原图"},
    {TextId::Zoom, "缩放"},
    {TextId::Fit, "适合"},
    {TextId::NoImageLoaded, "未加载图像"},
    {TextId::SetNumericValue, "设置数值"},
    {TextId::Value, "值"},
    {TextId::Apply, "应用"},
    {TextId::Cancel, "取消"},
    {TextId::InvalidValueFormat, "{label} 的值无效。"},
    {TextId::SetValueFormat, "已设置 {label}。"},
    {TextId::OpenDroppedImageTitle, "打开拖放的图像？"},
    {TextId::ReplaceDroppedImage, "用拖放的图像替换当前图像？"},
    {TextId::Open, "打开"},
    {TextId::DeletePaletteTitle, "删除调色板？"},
    {TextId::DeleteSavedPalette, "删除这个已保存的调色板？"},
    {TextId::Delete, "删除"},
    {TextId::PaletteAlreadyExistsTitle, "调色板已存在"},
    {TextId::PaletteAlreadyExistsFormat, "{name} 已存在。"},
    {TextId::Overwrite, "覆盖"},
    {TextId::KeepBoth, "保留两者"},
    {TextId::NameImportedPaletteTitle, "命名导入的调色板"},
    {TextId::PaletteName, "调色板名称"},
    {TextId::PaletteColorTitle, "调色板颜色"},
    {TextId::AddPaletteColor, "添加调色板颜色"},
    {TextId::EditPaletteColor, "编辑调色板颜色"},
    {TextId::Add, "添加"},
    {TextId::DeleteColor, "删除颜色"},
    {TextId::SavePaletteAsTitle, "调色板另存为"},
    {TextId::ImagesFilter, "图像"},
    {TextId::AllFilesFilter, "所有文件"},
    {TextId::LospecPalettesFilter, "Lospec 调色板"},
    {TextId::PngImageFilter, "PNG 图像"},
    {TextId::StatusOpenImageToBegin, "打开图像开始。"},
    {TextId::StatusPreviewUpdatedFormat, "预览已在 {ms} 毫秒内更新。"},
    {TextId::StatusLanguageChangedFormat, "语言已更改为 {language}。"},
};

constexpr Translation kChineseTraditional[] = {
    {TextId::LanguageWindowTitle, "語言"},
    {TextId::ChooseLanguage, "選擇語言"},
    {TextId::AboutWindowTitle, "關於 Pixelizer"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "關於 Pixelizer"},
    {TextId::AboutProjectCredit, "Pixelizer 作者：Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo。依 MIT 授權條款發布。"},
    {TextId::AboutThirdPartyTitle, "第三方授權與致謝"},
    {TextId::AboutDependenciesTitle, "相依項目"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 來自 libsdl-org/SDL，採用 zlib 授權。"},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 來自 ocornut/imgui，採用 MIT 授權。"},
    {TextId::AboutDependencyStb, "stb 來自 nothings/stb，提交為 31c1ad37456438565541f4919958214b6e762fb4，採用公有領域/MIT 雙授權。"},
    {TextId::AboutPalettesTitle, "內建調色盤"},
    {TextId::AboutPalettesCredit, "預設調色盤檔案來自 Lospec。原始調色盤頁面連結列於 THIRD_PARTY.md。"},
    {TextId::AboutAssetsCredit, "README 截圖與圖示檔案是本專案的原創資源。"},
    {TextId::Close, "關閉"},
    {TextId::OpenImage, "開啟影像"},
    {TextId::ImportPalette, "匯入調色盤"},
    {TextId::ExportPng, "匯出 PNG"},
    {TextId::TwoViews, "雙視圖"},
    {TextId::OneView, "單視圖"},
    {TextId::ShowOriginalAndResult, "顯示原圖與結果視圖。"},
    {TextId::ShowOnlyResult, "只顯示結果視圖。"},
    {TextId::StackViews, "堆疊視圖"},
    {TextId::SideBySide, "並排顯示"},
    {TextId::Pixelize, "像素化"},
    {TextId::PixelSize, "像素大小"},
    {TextId::BlockSample, "色塊取樣"},
    {TextId::Average, "平均"},
    {TextId::Weighted, "加權"},
    {TextId::UsePalette, "使用調色盤"},
    {TextId::PreserveTransparency, "保留透明度"},
    {TextId::NoPalettesSaved, "沒有已儲存的調色盤。"},
    {TextId::UnsavedPalette, "未儲存的調色盤"},
    {TextId::Palette, "調色盤"},
    {TextId::NewPalette, "新增調色盤"},
    {TextId::Save, "儲存"},
    {TextId::SaveNew, "另存新檔"},
    {TextId::DeletePalette, "刪除調色盤"},
    {TextId::PaletteCountFormat, "%zu / %zu 種顏色"},
    {TextId::AddColorToBegin, "新增一種顏色開始。"},
    {TextId::AddColor, "新增顏色"},
    {TextId::MaxColors, "最大顏色數"},
    {TextId::ColorLevels, "顏色層級"},
    {TextId::Dithering, "抖色"},
    {TextId::Mode, "模式"},
    {TextId::None, "無"},
    {TextId::Pattern, "圖案"},
    {TextId::Amount, "數量"},
    {TextId::Adjustments, "調整"},
    {TextId::Brightness, "亮度"},
    {TextId::Contrast, "對比"},
    {TextId::Gamma, "伽瑪"},
    {TextId::Saturation, "飽和度"},
    {TextId::Tint, "色調"},
    {TextId::TintStrength, "色調強度"},
    {TextId::ResetAdjustments, "重設調整"},
    {TextId::Result, "結果"},
    {TextId::Original, "原圖"},
    {TextId::Zoom, "縮放"},
    {TextId::Fit, "符合"},
    {TextId::NoImageLoaded, "尚未載入影像"},
    {TextId::Value, "值"},
    {TextId::Apply, "套用"},
    {TextId::Cancel, "取消"},
    {TextId::Open, "開啟"},
    {TextId::Delete, "刪除"},
    {TextId::Overwrite, "覆寫"},
    {TextId::KeepBoth, "保留兩者"},
    {TextId::PaletteName, "調色盤名稱"},
    {TextId::Add, "新增"},
    {TextId::DeleteColor, "刪除顏色"},
    {TextId::ImagesFilter, "影像"},
    {TextId::AllFilesFilter, "所有檔案"},
    {TextId::PngImageFilter, "PNG 影像"},
    {TextId::StatusOpenImageToBegin, "開啟影像開始。"},
    {TextId::StatusPreviewUpdatedFormat, "預覽已在 {ms} 毫秒內更新。"},
    {TextId::StatusLanguageChangedFormat, "語言已變更為 {language}。"},
};

constexpr Translation kKorean[] = {
    {TextId::LanguageWindowTitle, "언어"},
    {TextId::ChooseLanguage, "언어 선택"},
    {TextId::AboutWindowTitle, "Pixelizer 정보"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Pixelizer 정보"},
    {TextId::AboutProjectCredit, "Pixelizer 제작: Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. MIT 라이선스로 배포됩니다."},
    {TextId::AboutThirdPartyTitle, "타사 라이선스 및 크레딧"},
    {TextId::AboutDependenciesTitle, "의존성"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4는 libsdl-org/SDL에서 제공되며 zlib 라이선스를 따릅니다."},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7은 ocornut/imgui에서 제공되며 MIT 라이선스를 따릅니다."},
    {TextId::AboutDependencyStb, "stb는 nothings/stb의 커밋 31c1ad37456438565541f4919958214b6e762fb4이며 public-domain/MIT 이중 라이선스를 사용합니다."},
    {TextId::AboutPalettesTitle, "포함된 팔레트"},
    {TextId::AboutPalettesCredit, "기본 팔레트 파일은 Lospec에서 가져왔습니다. 원본 팔레트 페이지 링크는 THIRD_PARTY.md에 있습니다."},
    {TextId::AboutAssetsCredit, "README 스크린샷과 아이콘 파일은 프로젝트의 원본 자산입니다."},
    {TextId::Close, "닫기"},
    {TextId::OpenImage, "이미지 열기"},
    {TextId::ImportPalette, "팔레트 가져오기"},
    {TextId::ExportPng, "PNG 내보내기"},
    {TextId::TwoViews, "두 보기"},
    {TextId::OneView, "한 보기"},
    {TextId::Pixelize, "픽셀화"},
    {TextId::PixelSize, "픽셀 크기"},
    {TextId::BlockSample, "블록 샘플"},
    {TextId::Average, "평균"},
    {TextId::Weighted, "가중"},
    {TextId::UsePalette, "팔레트 사용"},
    {TextId::PreserveTransparency, "투명도 유지"},
    {TextId::NoPalettesSaved, "저장된 팔레트가 없습니다."},
    {TextId::UnsavedPalette, "저장되지 않은 팔레트"},
    {TextId::Palette, "팔레트"},
    {TextId::NewPalette, "새 팔레트"},
    {TextId::Save, "저장"},
    {TextId::SaveNew, "새로 저장"},
    {TextId::DeletePalette, "팔레트 삭제"},
    {TextId::PaletteCountFormat, "%zu / %zu 색상"},
    {TextId::AddColorToBegin, "시작하려면 색상을 추가하세요."},
    {TextId::AddColor, "색상 추가"},
    {TextId::MaxColors, "최대 색상"},
    {TextId::ColorLevels, "색상 단계"},
    {TextId::Dithering, "디더링"},
    {TextId::Mode, "모드"},
    {TextId::None, "없음"},
    {TextId::Pattern, "패턴"},
    {TextId::Amount, "양"},
    {TextId::Adjustments, "조정"},
    {TextId::Brightness, "밝기"},
    {TextId::Contrast, "대비"},
    {TextId::Saturation, "채도"},
    {TextId::Tint, "색조"},
    {TextId::TintStrength, "색조 강도"},
    {TextId::ResetAdjustments, "조정 초기화"},
    {TextId::Result, "결과"},
    {TextId::Original, "원본"},
    {TextId::Fit, "맞춤"},
    {TextId::NoImageLoaded, "이미지가 로드되지 않음"},
    {TextId::Value, "값"},
    {TextId::Apply, "적용"},
    {TextId::Cancel, "취소"},
    {TextId::Open, "열기"},
    {TextId::Delete, "삭제"},
    {TextId::Overwrite, "덮어쓰기"},
    {TextId::KeepBoth, "둘 다 유지"},
    {TextId::PaletteName, "팔레트 이름"},
    {TextId::Add, "추가"},
    {TextId::DeleteColor, "색상 삭제"},
    {TextId::ImagesFilter, "이미지"},
    {TextId::AllFilesFilter, "모든 파일"},
    {TextId::PngImageFilter, "PNG 이미지"},
    {TextId::StatusOpenImageToBegin, "시작하려면 이미지를 여세요."},
    {TextId::StatusPreviewUpdatedFormat, "미리보기가 {ms} ms 안에 업데이트되었습니다."},
    {TextId::StatusLanguageChangedFormat, "언어가 {language}(으)로 변경되었습니다."},
};

constexpr Translation kJapanese[] = {
    {TextId::LanguageWindowTitle, "言語"},
    {TextId::ChooseLanguage, "言語を選択"},
    {TextId::AboutWindowTitle, "Pixelizer について"},
    {TextId::AboutButtonLabel, "🛈"},
    {TextId::AboutButtonTooltip, "Pixelizer について"},
    {TextId::AboutProjectCredit, "Pixelizer 制作: Jon Tamayo"},
    {TextId::AboutProjectLicense, "Copyright (c) 2026 Jon Tamayo. MIT License の下で公開されています。"},
    {TextId::AboutThirdPartyTitle, "サードパーティのライセンスとクレジット"},
    {TextId::AboutDependenciesTitle, "依存関係"},
    {TextId::AboutDependencySdl, "SDL3 release-3.4.4 は libsdl-org/SDL 由来で、zlib ライセンスです。"},
    {TextId::AboutDependencyImGui, "Dear ImGui v1.92.7 は ocornut/imgui 由来で、MIT ライセンスです。"},
    {TextId::AboutDependencyStb, "stb は nothings/stb のコミット 31c1ad37456438565541f4919958214b6e762fb4 で、public-domain/MIT のデュアルライセンスです。"},
    {TextId::AboutPalettesTitle, "同梱パレット"},
    {TextId::AboutPalettesCredit, "既定のパレットファイルは Lospec から同梱しています。元のパレットページへのリンクは THIRD_PARTY.md に記載しています。"},
    {TextId::AboutAssetsCredit, "README のスクリーンショットとアイコンファイルは、このプロジェクトのオリジナル素材です。"},
    {TextId::Close, "閉じる"},
    {TextId::OpenImage, "画像を開く"},
    {TextId::ImportPalette, "パレットを読み込む"},
    {TextId::ExportPng, "PNGを書き出す"},
    {TextId::TwoViews, "2画面"},
    {TextId::OneView, "1画面"},
    {TextId::Pixelize, "ピクセル化"},
    {TextId::PixelSize, "ピクセルサイズ"},
    {TextId::BlockSample, "ブロックサンプル"},
    {TextId::Average, "平均"},
    {TextId::Weighted, "加重"},
    {TextId::UsePalette, "パレットを使用"},
    {TextId::PreserveTransparency, "透明度を保持"},
    {TextId::NoPalettesSaved, "保存済みパレットはありません。"},
    {TextId::UnsavedPalette, "未保存のパレット"},
    {TextId::Palette, "パレット"},
    {TextId::NewPalette, "新規パレット"},
    {TextId::Save, "保存"},
    {TextId::SaveNew, "新規保存"},
    {TextId::DeletePalette, "パレットを削除"},
    {TextId::PaletteCountFormat, "%zu / %zu 色"},
    {TextId::AddColorToBegin, "色を追加して開始します。"},
    {TextId::AddColor, "色を追加"},
    {TextId::MaxColors, "最大色数"},
    {TextId::ColorLevels, "色レベル"},
    {TextId::Dithering, "ディザリング"},
    {TextId::Mode, "モード"},
    {TextId::None, "なし"},
    {TextId::Pattern, "パターン"},
    {TextId::Amount, "量"},
    {TextId::Adjustments, "調整"},
    {TextId::Brightness, "明るさ"},
    {TextId::Contrast, "コントラスト"},
    {TextId::Saturation, "彩度"},
    {TextId::Tint, "色合い"},
    {TextId::TintStrength, "色合いの強さ"},
    {TextId::ResetAdjustments, "調整をリセット"},
    {TextId::Result, "結果"},
    {TextId::Original, "元画像"},
    {TextId::Fit, "合わせる"},
    {TextId::NoImageLoaded, "画像が読み込まれていません"},
    {TextId::Value, "値"},
    {TextId::Apply, "適用"},
    {TextId::Cancel, "キャンセル"},
    {TextId::Open, "開く"},
    {TextId::Delete, "削除"},
    {TextId::Overwrite, "上書き"},
    {TextId::KeepBoth, "両方残す"},
    {TextId::PaletteName, "パレット名"},
    {TextId::Add, "追加"},
    {TextId::DeleteColor, "色を削除"},
    {TextId::ImagesFilter, "画像"},
    {TextId::AllFilesFilter, "すべてのファイル"},
    {TextId::PngImageFilter, "PNG画像"},
    {TextId::StatusOpenImageToBegin, "画像を開いて開始してください。"},
    {TextId::StatusPreviewUpdatedFormat, "プレビューを {ms} ms で更新しました。"},
    {TextId::StatusLanguageChangedFormat, "言語を {language} に変更しました。"},
};

template <std::size_t N>
const char* find_translation(const Translation (&table)[N], TextId id)
{
    for (const Translation& translation : table) {
        if (translation.id == id) {
            return translation.text;
        }
    }
    return nullptr;
}

const char* find_localized_translation(Language language, TextId id)
{
    switch (language) {
    case Language::English:
        return find_translation(kEnglish, id);
    case Language::Spanish:
        return find_translation(kSpanish, id);
    case Language::French:
        return find_translation(kFrench, id);
    case Language::German:
        return find_translation(kGerman, id);
    case Language::Danish:
        return find_translation(kDanish, id);
    case Language::Swedish:
        return find_translation(kSwedish, id);
    case Language::Norwegian:
        return find_translation(kNorwegian, id);
    case Language::Czech:
        return find_translation(kCzech, id);
    case Language::Italian:
        return find_translation(kItalian, id);
    case Language::Greek:
        return find_translation(kGreek, id);
    case Language::Polish:
        return find_translation(kPolish, id);
    case Language::Finnish:
        return find_translation(kFinnish, id);
    case Language::Ukrainian:
        return find_translation(kUkrainian, id);
    case Language::Russian:
        return find_translation(kRussian, id);
    case Language::ChineseSimplified:
        return find_translation(kChineseSimplified, id);
    case Language::ChineseTraditional:
        return find_translation(kChineseTraditional, id);
    case Language::Korean:
        return find_translation(kKorean, id);
    case Language::Japanese:
        return find_translation(kJapanese, id);
    case Language::Count:
        break;
    }
    return nullptr;
}

void replace_all(std::string& value, std::string_view from, std::string_view to)
{
    if (from.empty()) {
        return;
    }

    std::size_t position = 0;
    while ((position = value.find(from, position)) != std::string::npos) {
        value.replace(position, from.size(), to);
        position += to.size();
    }
}

} // namespace

const std::array<LanguageDefinition, kLanguageCount>& language_definitions()
{
    return kLanguages;
}

const LanguageDefinition& language_definition(Language language)
{
    const auto index = static_cast<std::size_t>(language);
    if (index >= kLanguages.size()) {
        return kLanguages[0];
    }
    return kLanguages[index];
}

const char* translate(Language language, TextId id)
{
    if (const char* localized = find_localized_translation(language, id)) {
        return localized;
    }
    if (const char* english = find_translation(kEnglish, id)) {
        return english;
    }
    return "";
}

std::string format_translation(
    Language language,
    TextId id,
    std::initializer_list<std::pair<std::string_view, std::string_view>> values)
{
    std::string formatted = translate(language, id);
    for (const auto& [key, value] : values) {
        std::string marker;
        marker.reserve(key.size() + 2U);
        marker.push_back('{');
        marker.append(key);
        marker.push_back('}');
        replace_all(formatted, marker, value);
    }
    return formatted;
}

} // namespace pixelizer
