#pragma once

#include <array>
#include <cstddef>
#include <initializer_list>
#include <string>
#include <string_view>

namespace pixelizer {

enum class Language {
    English,
    Spanish,
    French,
    German,
    Danish,
    Swedish,
    Norwegian,
    Czech,
    Italian,
    Greek,
    Polish,
    Finnish,
    Ukrainian,
    Russian,
    ChineseSimplified,
    ChineseTraditional,
    Korean,
    Japanese,
    Count,
};

struct LanguageDefinition {
    Language language;
    const char* code;
    const char* english_name;
    const char* native_name;
};

enum class TextId {
    LanguageWindowTitle,
    ChooseLanguage,
    AboutWindowTitle,
    AboutButtonLabel,
    AboutButtonTooltip,
    AboutProjectCredit,
    AboutProjectLicense,
    AboutThirdPartyTitle,
    AboutDependenciesTitle,
    AboutDependencySdl,
    AboutDependencyImGui,
    AboutDependencyStb,
    AboutPalettesTitle,
    AboutPalettesCredit,
    AboutAssetsCredit,
    Close,
    OpenImage,
    ImportPalette,
    ExportPng,
    TwoViews,
    OneView,
    ShowOriginalAndResult,
    ShowOnlyResult,
    StackViews,
    SideBySide,
    ShowResultTop,
    ShowOriginalLeft,
    Pixelize,
    PixelSize,
    BlockSample,
    Average,
    Weighted,
    UsePalette,
    NoPalettesSaved,
    UnsavedPalette,
    Palette,
    NewPalette,
    Save,
    SaveNew,
    DeletePalette,
    PaletteCountFormat,
    AddColorToBegin,
    EditColorFormat,
    AddColor,
    MaxColors,
    ColorLevels,
    Dithering,
    Mode,
    None,
    Bayer,
    BlueNoise,
    FloydSteinberg,
    JarvisJudiceNinke,
    Atkinson,
    Riemersma,
    Pattern,
    Amount,
    Adjustments,
    Brightness,
    Contrast,
    Gamma,
    Saturation,
    InputBlack,
    InputWhite,
    OutputBlack,
    OutputWhite,
    Tint,
    TintStrength,
    ResetAdjustments,
    Result,
    Original,
    Zoom,
    Fit,
    NoImageLoaded,
    SetNumericValue,
    Value,
    Apply,
    Cancel,
    InvalidValueFormat,
    SetValueFormat,
    OpenDroppedImageTitle,
    ReplaceDroppedImage,
    Open,
    DeletePaletteTitle,
    DeleteSavedPalette,
    Delete,
    PaletteAlreadyExistsTitle,
    PaletteAlreadyExistsFormat,
    Overwrite,
    KeepBoth,
    NameImportedPaletteTitle,
    PaletteName,
    PaletteColorTitle,
    AddPaletteColor,
    EditPaletteColor,
    Add,
    DeleteColor,
    SavePaletteAsTitle,
    ImagesFilter,
    AllFilesFilter,
    LospecPalettesFilter,
    PngImageFilter,
    StatusOpenImageToBegin,
    StatusPreviewUpdatedFormat,
    StatusImageLoadFailedFormat,
    StatusLoadedFormat,
    StatusPaletteImportFailedFormat,
    StatusImportedPaletteFormat,
    StatusOverwrotePaletteFormat,
    StatusStartedNewPalette,
    StatusPaletteFull,
    StatusPaletteColorMissing,
    StatusUseSaveNew,
    StatusPaletteSaveFailedFormat,
    StatusSavedPaletteFormat,
    StatusAddColorBeforeSaving,
    StatusNoPaletteSelected,
    StatusPaletteDeleteFailedFormat,
    StatusDeletedPaletteFormat,
    StatusExportSkipped,
    StatusExportFailedFormat,
    StatusExportedFormat,
    StatusNothingToUndo,
    StatusUndid,
    StatusNothingToRedo,
    StatusRedid,
    StatusAddedColor,
    StatusUpdatedColor,
    StatusDeletedColor,
    StatusSdlInitFailedFormat,
    StatusSdlCreateWindowFailedFormat,
    StatusSdlCreateRendererFailedFormat,
    StatusSdlCreateTextureFailedFormat,
    StatusLanguageChangedFormat,
    Count,
};

constexpr std::size_t kLanguageCount = static_cast<std::size_t>(Language::Count);
constexpr std::size_t kTextCount = static_cast<std::size_t>(TextId::Count);

const std::array<LanguageDefinition, kLanguageCount>& language_definitions();
const LanguageDefinition& language_definition(Language language);
const char* translate(Language language, TextId id);
std::string format_translation(
    Language language,
    TextId id,
    std::initializer_list<std::pair<std::string_view, std::string_view>> values);

} // namespace pixelizer
